// GENERATED by tools/gen_data.js from minecraft-data (1.16.5 / protocol 754). DO NOT EDIT.
#pragma once
#include <stdint.h>
namespace mc {
namespace biome {  // biome ids included in the dimension codec
constexpr uint8_t Ocean = 0;
constexpr uint8_t Plains = 1;
constexpr uint8_t Desert = 2;
constexpr uint8_t Mountains = 3;
constexpr uint8_t Forest = 4;
constexpr uint8_t Taiga = 5;
constexpr uint8_t Swamp = 6;
constexpr uint8_t River = 7;
constexpr uint8_t FrozenOcean = 10;
constexpr uint8_t FrozenRiver = 11;
constexpr uint8_t SnowyTundra = 12;
constexpr uint8_t MushroomFields = 14;
constexpr uint8_t Beach = 16;
constexpr uint8_t WoodedHills = 18;
constexpr uint8_t Jungle = 21;
constexpr uint8_t DeepOcean = 24;
constexpr uint8_t StoneShore = 25;
constexpr uint8_t SnowyBeach = 26;
constexpr uint8_t BirchForest = 27;
constexpr uint8_t DarkForest = 29;
constexpr uint8_t SnowyTaiga = 30;
constexpr uint8_t Savanna = 35;
constexpr uint8_t Badlands = 37;
constexpr uint8_t WarmOcean = 44;
constexpr uint8_t LukewarmOcean = 45;
constexpr uint8_t ColdOcean = 46;
constexpr uint8_t DeepColdOcean = 49;
constexpr uint8_t TheVoid = 127;
constexpr uint8_t SunflowerPlains = 129;
}
}  // namespace mc
