#!/usr/bin/env python3
"""Generate static redstone properties from the official 1.16.5 runtime.

Since the move to 1.21.8 this is the source of record only: its values were saved by
snapshot_1_16_5.js into states-1.16.5.json, which gen_data.js carries over to the 1.21.8
block states (collision boxes now come from minecraft-data). Running it again rewrites
the tables in the 1.16.5 numbering; rerun snapshot_1_16_5.js and gen_data.js after it.

Requires Java 11+ with source-file launch support. The verified jar and temporary
files stay under ignored tools/vanilla/. No Minecraft server/EULA is launched.
"""
import hashlib
import json
from pathlib import Path
import re
import subprocess
import urllib.request

ROOT = Path(__file__).resolve().parents[2]
CACHE = ROOT / 'tools/vanilla'
SHA1 = '1b557e7b033b583cd9f66746b7a9ab1ec1673ced'
CACHE.mkdir(exist_ok=True)
jar = CACHE / 'server.jar'
if not jar.exists():
    urllib.request.urlretrieve(f'https://piston-data.mojang.com/v1/objects/{SHA1}/server.jar', jar)
if hashlib.sha1(jar.read_bytes()).hexdigest() != SHA1:
    raise SystemExit('Official 1.16.5 server checksum mismatch')
output = CACHE / 'redstone-states.tsv'
subprocess.run(['java', '-Dlog4j2.formatMsgNoLookups=true', '-cp', str(jar),
                str(ROOT / 'tools/redstone/StateProperties.java'), str(output)], cwd=CACHE, check=True)
rows = [line.split('\t') for line in output.read_text().splitlines()]
# Check every block's state-ID range against the committed registry. Also check
# property names/value indices against minecraft-data when its test dependency is
# installed. No state values from that package are used to infer physical behaviour.
registry = (ROOT / 'lib/mcore/src/mc/data/registry_data.cpp').read_text()
blocks = re.findall(r'^\{"([a-z_0-9]+)",(\d+),(\d+),(\d+),(\d+),(\d+),', registry, re.M)
count = int(re.search(r'NUM_STATES = (\d+)', (ROOT / 'lib/mcore/src/mc/data/ids_gen.h').read_text())[1])
assert len(rows) == count
covered = set()
for name, start, default, size, prop_start, prop_count in blocks:
    start, size = int(start), int(size)
    if start + size > count or not rows[start][2].startswith('Block{minecraft:' + name + '}'):
        continue # other generated tables have different layouts
    for i in range(start, start + size):
        assert int(rows[i][0]) == i and rows[i][2].startswith('Block{minecraft:' + name + '}'), (name, i)
        covered.add(i)
assert len(covered) == count, 'Registry state ID mismatch'
md = ROOT / 'test/node_modules/minecraft-data/minecraft-data/data/pc/1.16.2/blocks.json'
if md.exists():
    for block in json.loads(md.read_text()):
        for i in range(block['minStateId'], block['maxStateId'] + 1):
            remainder = i - block['minStateId']
            props = {}
            for prop in reversed(block['states']):
                value = remainder % prop['num_values']
                remainder //= prop['num_values']
                vals = prop.get('values', ['true', 'false'] if prop['type'] == 'bool' else None)
                props[prop['name']] = vals[value] if vals else str(value)
            actual = dict(re.findall(r'([a-z_0-9]+)=([a-z_0-9]+)', rows[i][2]))
            assert actual == props, (i, actual, props)
values = [int(row[1]) for row in rows]
text = ('// GENERATED by tools/redstone/generate.py from the official 1.16.5 runtime.\n'
        '// Jar SHA-1: ' + SHA1 + '\n'
        '// bits 0..3: light; 4: conductor; 5: signal source; 6..11: sturdy faces (D U N S W E); 12..15: note instrument.\n'
        '#include "mc/registry.h"\nnamespace mc {\nconst uint16_t REDSTONE_STATE_PROPERTIES[NUM_STATES] = {\n')
for i in range(0, count, 24):
    text += '    ' + ','.join(str(v) for v in values[i:i + 24]) + ',\n'
text += '};\n// bits 0..2: PushReaction; 3: block entity; 4: unbreakable.\n'
text += 'const uint8_t PISTON_STATE_PROPERTIES[NUM_STATES] = {\n'
for i in range(0, count, 32):
    text += '    ' + ','.join(row[3] for row in rows[i:i + 32]) + ',\n'
text += '};\n} // namespace mc\n'
(ROOT / 'lib/mcore/src/mc/data/redstone_data.cpp').write_text(text)
shapes = {}
offsets = []
data = []
for row in rows:
    key = row[4]
    if key not in shapes:
        shapes[key] = len(data)
        boxes = key.split(';') if key else []
        assert len(boxes) <= 15, 'Piston collision scratch capacity exceeded'
        data.append(len(boxes))
        for box in boxes:
            data.extend(map(int, box.split(',')))
    offsets.append(shapes[key])
assert len(data) < 65536 and max(data) <= 127
text = ('// GENERATED by tools/redstone/generate.py from the pinned official 1.16.5 runtime.\n'
        '// Each shape: box count, then x0,y0,z0,x1,y1,z1 in thirty-seconds.\n'
        '#include "mc/registry.h"\nnamespace mc {\nconst uint16_t COLLISION_SHAPE_OFFSETS[NUM_STATES] = {\n')
for i in range(0, count, 24):
    text += '    ' + ','.join(map(str, offsets[i:i + 24])) + ',\n'
text += '};\nconst int8_t COLLISION_SHAPES[] = {\n'
for i in range(0, len(data), 32):
    text += '    ' + ','.join(map(str, data[i:i + 32])) + ',\n'
text += '};\n} // namespace mc\n'
(ROOT / 'lib/mcore/src/mc/data/collision_data.cpp').write_text(text)
print(f'Generated and checked {count} state properties')
print(f'{len(shapes)} collision shapes, {len(data) + 2 * count} flash bytes')
