#!/usr/bin/env node
// Translates the block state ids in host/tests/data/redstone_traces.inc (recorded by
// trace.py on the official 1.16.5 server) to the 1.21.8 numbering: each 1.16.5 state is
// decoded to its block name and properties and encoded again. Run once after trace.py.
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..', '..');
const md = path.join(path.dirname(require.resolve('minecraft-data/package.json', { paths: [path.join(ROOT, 'tools')] })), 'minecraft-data', 'data', 'pc');
const oldBlocks = JSON.parse(fs.readFileSync(path.join(md, '1.16.2', 'blocks.json')));
const newBlocks = JSON.parse(fs.readFileSync(path.join(md, '1.21.8', 'blocks.json')));
const RENAMED = { grass: 'short_grass', grass_path: 'dirt_path' };
const labels = (p) => p.values || (p.type === 'bool' ? ['true', 'false'] : Array.from({ length: p.num_values }, (_, i) => String(i)));

function decode(state) {
  const b = oldBlocks.find((x) => state >= x.minStateId && state <= x.maxStateId);
  let rem = state - b.minStateId;
  const props = {};
  for (let i = b.states.length - 1; i >= 0; i--) {
    const p = b.states[i];
    props[p.name] = { label: labels(p)[rem % p.num_values], index: rem % p.num_values, values: labels(p) };
    rem = Math.floor(rem / p.num_values);
  }
  // 1.17 split the cauldron: one with water is a block of its own
  if (b.name === 'cauldron' && props.level.label !== '0') return { name: 'water_cauldron', props };
  return { name: RENAMED[b.name] || b.name, props };
}

function encode({ name, props }) {
  const b = newBlocks.find((x) => x.name === name);
  if (!b) throw new Error('no block ' + name + ' in 1.21.8');
  // the default state's value indices, for properties 1.16.5 did not have
  const defaults = [];
  let rem = b.defaultState - b.minStateId;
  for (let i = b.states.length - 1; i >= 0; i--) {
    defaults[i] = rem % b.states[i].num_values;
    rem = Math.floor(rem / b.states[i].num_values);
  }
  let s = 0;
  b.states.forEach((p, i) => {
    const vals = labels(p);
    const old = props[p.name];
    let v = defaults[i];
    if (old) {
      // by label: minecraft-data 1.16 lists ints that do not start at 0 with their values
      v = vals.indexOf(old.label);
      if (v < 0) throw new Error(`${name}.${p.name}=${old.label} has no 1.21.8 value`);
    }
    s = s * p.num_values + v;
  });
  return b.minStateId + s;
}

const file = path.join(ROOT, 'host', 'tests', 'data', 'redstone_traces.inc');
let src = fs.readFileSync(file, 'utf8');
if (src.includes('remapped to 1.21.8')) throw new Error('already remapped');
const map = (n) => (n === 0 ? 0 : encode(decode(n)));
src = src.replace(/(setBlock\([^;]*?, )(\d+)\)/g, (m, a, n) => a + map(+n) + ')');
src = src.replace(/blockIdOf\((\d+)\)/g, (m, n) => 'blockIdOf(' + map(+n) + ')');
src = src.replace('// Generated by tools/redstone/trace.py from the official 1.16.5 server.',
  '// Generated by tools/redstone/trace.py from the official 1.16.5 server; block states\n// remapped to 1.21.8 by tools/redstone/remap_traces.js.');
fs.writeFileSync(file, src);
console.log('remapped', file);
