#!/usr/bin/env node
// Generates the static registry tables of the server core from the
// PrismarineJS minecraft-data package (protocol 754 / Minecraft 1.16.5).
//
//   cd tools && npm install && node gen_data.js
//
// The generated files are committed, so you only need this to regenerate them.
'use strict';
const fs = require('fs');
const path = require('path');
const nbt = require('prismarine-nbt');

const OUT = path.join(__dirname, '..', 'lib', 'mcore', 'src', 'mc', 'data');
fs.mkdirSync(OUT, { recursive: true });

const mdRoot = path.join(path.dirname(require.resolve('minecraft-data/package.json')), 'minecraft-data', 'data', 'pc');
const load = (ver, f) => JSON.parse(fs.readFileSync(path.join(mdRoot, ver, f)));
const blocks = load('1.16.2', 'blocks.json');
const items = load('1.16.2', 'items.json');
const recipes = load('1.16.2', 'recipes.json');
const entities = load('1.16.2', 'entities.json');
const protocol = load('1.16.2', 'protocol.json');
const loginPacket = load('1.16.2', 'loginPacket.json');
const foods = load('1.16.1', 'foods.json');

const camel = (s) => s.split('_').map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
const fl = (x) => { let s = String(x); if (!/[.e]/i.test(s)) s += '.0'; return s + 'f'; };
const cstr = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
const HDR = '// GENERATED by tools/gen_data.js from minecraft-data (1.16.5 / protocol 754). DO NOT EDIT.\n';

function wrap(arr, per = 16) {
  const lines = [];
  for (let i = 0; i < arr.length; i += per) lines.push('  ' + arr.slice(i, i + per).join(', '));
  return lines.join(',\n');
}

// ------------------------------------------------------------------ ids
const NUM_BLOCKS = blocks.length;
const NUM_STATES = Math.max(...blocks.map((b) => b.maxStateId)) + 1;
const maxItemId = Math.max(...items.map((i) => i.id));
const NUM_ITEMS = maxItemId + 1;
const itemById = new Array(NUM_ITEMS).fill(null);
for (const it of items) itemById[it.id] = it;
const itemByName = {};
for (const it of items) itemByName[it.name] = it;
const blockByName = {};
for (const b of blocks) blockByName[b.name] = b;
for (let i = 0; i < blocks.length; i++) if (blocks[i].id !== i) throw new Error('block ids not contiguous');

// ------------------------------------------------------------------ block ids header
{
  let s = HDR + '#pragma once\n#include <stdint.h>\nnamespace mc {\n';
  s += `constexpr int NUM_BLOCKS = ${NUM_BLOCKS};\nconstexpr int NUM_STATES = ${NUM_STATES};\nconstexpr int NUM_ITEMS = ${NUM_ITEMS};\n`;
  s += 'namespace blk {  // block ids\n';
  for (const b of blocks) s += `constexpr uint16_t ${camel(b.name)} = ${b.id};\n`;
  s += '}\nnamespace bs {  // default block state of each block\n';
  for (const b of blocks) s += `constexpr uint16_t ${camel(b.name)} = ${b.defaultState};\n`;
  s += '}\nnamespace itm {  // item ids\n';
  for (const it of items) s += `constexpr uint16_t ${camel(it.name)} = ${it.id};\n`;
  s += '}\n}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'ids_gen.h'), s);
}

// ------------------------------------------------------------------ entity ids
{
  let s = HDR + '#pragma once\n#include <stdint.h>\nnamespace mc {\nnamespace ent {  // entity type ids\n';
  for (const e of entities) s += `constexpr uint16_t ${camel(e.name)} = ${e.id};\n`;
  s += '}\n}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'entity_ids_gen.h'), s);
}

// ------------------------------------------------------------------ packet ids
{
  const mk = (dir) => {
    const m = protocol.play[dir].types.packet[1][0].type[1].mappings;
    return Object.entries(m).map(([id, name]) => `constexpr uint8_t ${camel(name)} = ${parseInt(id, 16)};`).join('\n');
  };
  let s = HDR + '#pragma once\n#include <stdint.h>\nnamespace mc {\nnamespace pkt {\n';
  s += 'namespace s2c {  // play: server -> client\n' + mk('toClient') + '\n}\n';
  s += 'namespace c2s {  // play: client -> server\n' + mk('toServer') + '\n}\n';
  s += '}\n}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'packet_ids_gen.h'), s);
}

// ------------------------------------------------------------------ block data
const NEEDS_SUPPORT_RE = /(_sapling|_tulip|^dandelion$|^poppy$|^blue_orchid$|^allium$|^azure_bluet$|^oxeye_daisy$|^cornflower$|^lily_of_the_valley$|^wither_rose$|^sunflower$|^lilac$|^rose_bush$|^peony$|^grass$|^tall_grass$|^fern$|^large_fern$|^dead_bush$|^wheat$|^carrots$|^potatoes$|^beetroots$|^melon_stem$|^pumpkin_stem$|^brown_mushroom$|^red_mushroom$|^sweet_berry_bush$|^sugar_cane$|^cactus$|^nether_sprout|_roots$|^crimson_fungus$|^warped_fungus$|^bamboo_sapling$)/;
const REPLACEABLE = new Set(['air', 'cave_air', 'void_air', 'water', 'lava', 'grass', 'tall_grass', 'fern', 'large_fern', 'seagrass', 'tall_seagrass', 'fire', 'soul_fire', 'vine', 'dead_bush', 'snow', 'structure_void', 'light']);
const GRAVITY = new Set(['sand', 'red_sand', 'gravel', 'anvil', 'chipped_anvil', 'damaged_anvil', 'white_concrete_powder', 'orange_concrete_powder', 'magenta_concrete_powder', 'light_blue_concrete_powder', 'yellow_concrete_powder', 'lime_concrete_powder', 'pink_concrete_powder', 'gray_concrete_powder', 'light_gray_concrete_powder', 'cyan_concrete_powder', 'purple_concrete_powder', 'blue_concrete_powder', 'brown_concrete_powder', 'green_concrete_powder', 'red_concrete_powder', 'black_concrete_powder']);
const WOODY = /(planks|_log$|_wood$|_stem$|_hyphae$|chest|crafting_table|bookshelf|barrel|_door$|_fence|_gate$|_sign|_slab$|_stairs$|_trapdoor|_pressure_plate|_button|jukebox|note_block|loom|lectern|cartography|fletching|smithing|composter|bamboo|ladder|beehive|bee_nest|campfire|banner|daylight|scaffolding|^bed$|_bed$)/;
const NONSOLID_NAMES = /(^|_)(sign|banner|button|pressure_plate|carpet)$/;

function toolClass(b) {
  // 1 pickaxe 2 axe 3 shovel 4 hoe 5 shears/sword(special) 0 hand
  const n = b.name;
  if (b.material === 'rock' || b.harvestTools) return 1;
  if (b.material === 'dirt') return 3;
  if (b.material === 'wool' || b.material === 'web' || /_leaves$/.test(n) || /^(leaves)$/.test(n)) return 5;
  if (b.material === 'wood' || WOODY.test(n)) return 2;
  if (/(sand|gravel|clay|dirt|soil|snow|mud|podzol|mycelium|grass_block|farmland|path|soul)/.test(n) && !/(stone|brick|glass|terracotta)/.test(n)) return 3;
  if (/(_stone|stone_|cobble|brick|obsidian|ore$|_ore$|terracotta|concrete$|furnace|anvil|iron|gold|diamond|emerald|lapis|quartz|netherrack|basalt|blackstone|prismarine|purpur|end_stone|bone_block|magma|glowstone|lantern|chain|bell|piston|dispenser|dropper|observer|hopper|cauldron|spawner|beacon|ender_chest|enchanting|brewing|grindstone|stonecutter|lodestone|netherite|ancient|crying|respawn|sandstone|coral)/.test(n)) return 1;
  return 0;
}

const propDefs = [];
const propKey = new Map();
const blockPropLists = [];
function propIndex(s) {
  const key = JSON.stringify([s.name, s.type, s.num_values, s.values || null]);
  if (propKey.has(key)) return propKey.get(key);
  const idx = propDefs.length;
  propDefs.push(s);
  propKey.set(key, idx);
  return idx;
}

// Primary drop per block (item id, min, max) derived from loot data, hand-tuned overrides below.
const blockLoot = load('1.16.2', 'blockLoot.json');
const lootByBlock = {};
for (const l of blockLoot) lootByBlock[l.block] = l.drops;
const DROP_NONE = new Set(['air', 'cave_air', 'void_air', 'water', 'lava', 'bedrock', 'fire', 'soul_fire', 'glass', 'ice', 'frosted_ice', 'spawner', 'barrier', 'end_portal', 'end_portal_frame', 'nether_portal', 'end_gateway', 'structure_void', 'structure_block', 'jigsaw', 'command_block', 'chain_command_block', 'repeating_command_block', 'budding_amethyst', 'piston_head', 'moving_piston', 'infested_stone', 'infested_cobblestone', 'infested_stone_bricks', 'infested_mossy_stone_bricks', 'infested_cracked_stone_bricks', 'infested_chiseled_stone_bricks', 'vine', 'tripwire', 'turtle_egg', 'nether_wart_block_none', 'dragon_egg_none', 'light']);
const DROP_ALIAS = {
  stone: ['cobblestone', 1, 1], grass_block: ['dirt', 1, 1], podzol: ['dirt', 1, 1], mycelium: ['dirt', 1, 1], coarse_dirt: ['dirt', 1, 1],
  coal_ore: ['coal', 1, 1], diamond_ore: ['diamond', 1, 1], emerald_ore: ['emerald', 1, 1], lapis_ore: ['lapis_lazuli', 4, 8],
  redstone_ore: ['redstone', 4, 5], nether_quartz_ore: ['quartz', 1, 1], nether_gold_ore: ['gold_nugget', 2, 6],
  glowstone: ['glowstone_dust', 2, 4], clay: ['clay_ball', 4, 4], snow_block: ['snowball', 4, 4], snow: ['snowball', 1, 1], melon: ['melon_slice', 3, 7],
  bookshelf: ['book', 3, 3], gravel: ['gravel', 1, 1], sea_lantern: ['prismarine_crystals', 2, 3], ender_chest: ['obsidian', 8, 8],
  redstone_wire: ['redstone', 1, 1], wall_torch: ['torch', 1, 1], soul_wall_torch: ['soul_torch', 1, 1], redstone_wall_torch: ['redstone_torch', 1, 1],
  dead_bush: ['stick', 0, 2], wheat: ['wheat_seeds', 1, 1], potatoes: ['potato', 1, 1], carrots: ['carrot', 1, 1], beetroots: ['beetroot_seeds', 1, 1],
  melon_stem: ['melon_seeds', 0, 0], pumpkin_stem: ['pumpkin_seeds', 0, 0], tall_grass: [null], grass: [null], fern: [null], large_fern: [null],
  oak_leaves: ['stick', 0, 2], spruce_leaves: ['stick', 0, 2], birch_leaves: ['stick', 0, 2], jungle_leaves: ['stick', 0, 2], acacia_leaves: ['stick', 0, 2], dark_oak_leaves: ['stick', 0, 2],
  cobweb: ['string', 1, 1], kelp_plant: ['kelp', 1, 1], bamboo_sapling: ['bamboo', 1, 1], sweet_berry_bush: ['sweet_berries', 1, 2], cocoa: ['cocoa_beans', 1, 1],
  lily_pad: ['lily_pad', 1, 1], tripwire: [null], weeping_vines_plant: [null], twisting_vines_plant: [null], nether_wart: ['nether_wart', 2, 4],
  white_wall_banner: ['white_banner', 1, 1], acacia_wall_sign: ['acacia_sign', 1, 1], birch_wall_sign: ['birch_sign', 1, 1], crimson_wall_sign: ['crimson_sign', 1, 1],
  dark_oak_wall_sign: ['dark_oak_sign', 1, 1], jungle_wall_sign: ['jungle_sign', 1, 1], oak_wall_sign: ['oak_sign', 1, 1], spruce_wall_sign: ['spruce_sign', 1, 1], warped_wall_sign: ['warped_sign', 1, 1],
  tall_seagrass: [null], seagrass: [null], cave_vines: [null], farmland: ['dirt', 1, 1], grass_path: ['dirt', 1, 1],
  stone_slab_double: [null], bee_nest: [null], beehive: ['beehive', 1, 1], iron_ore: ['iron_ore', 1, 1], gold_ore: ['gold_ore', 1, 1],
  ancient_debris: ['ancient_debris', 1, 1], shroomlight: ['shroomlight', 1, 1],
};
for (const [dye] of [['white'], ['orange'], ['magenta'], ['light_blue'], ['yellow'], ['lime'], ['pink'], ['gray'], ['light_gray'], ['cyan'], ['purple'], ['blue'], ['brown'], ['green'], ['red'], ['black']]) {
  DROP_ALIAS[dye + '_wall_banner'] = [dye + '_banner', 1, 1];
}
function dropFor(b) {
  if (DROP_NONE.has(b.name)) return [0, 0, 0];
  if (!b.diggable && b.name !== 'bedrock') return [0, 0, 0];
  if (b.name === 'bedrock') return [0, 0, 0];
  const al = DROP_ALIAS[b.name];
  if (al) {
    if (al[0] === null) return [0, 0, 0];
    const it = itemByName[al[0]];
    if (!it) throw new Error('drop alias item missing ' + al[0]);
    return [it.id, al[1], al[2]];
  }
  // Slab double / door halves: handled in code (count / half). Default: item with same name.
  const direct = itemByName[b.name];
  if (direct) return [direct.id, 1, 1];
  const loot = lootByBlock[b.name];
  if (loot) {
    const e = loot.find((x) => x.noSilkTouch) || loot.find((x) => !x.silkTouch);
    if (e && itemByName[e.item]) return [itemByName[e.item].id, (e.stackSizeRange && e.stackSizeRange[0]) || 1, (e.stackSizeRange && e.stackSizeRange[1]) || 1];
  }
  return [0, 0, 0];
}

// Light opacity. minecraft-data's filterLight is unreliable (leaves 0, tall grass and snow
// layers 15, stairs 15), so derive it from the vanilla rules: blocks that only dim light
// by one (water, leaves, ice, cobweb, slime, honey), non-occluding blocks 0, solid cubes 15.
const OPACITY_ONE = new Set(['water', 'bubble_column', 'ice', 'frosted_ice', 'cobweb', 'slime_block', 'honey_block']);
function lightOpacity(b) {
  if (OPACITY_ONE.has(b.name) || b.name.endsWith('_leaves')) return 1;
  if (b.transparent || b.boundingBox === 'empty') return 0;
  if (b.name === 'snow' || b.name.endsWith('_slab') || b.name.endsWith('_stairs') || b.name === 'farmland' ||
      b.name === 'grass_path' || b.name.endsWith('_carpet') || b.name === 'soul_sand' || b.name === 'lectern' ||
      b.name === 'enchanting_table' || b.name === 'stonecutter' || b.name === 'daylight_detector' || b.name.endsWith('_bed'))
    return 0;
  return 15;
}

const F = { COLLIDES: 1, TRANSPARENT: 2, DIGGABLE: 4, FLUID: 8, REPLACEABLE: 16, GRAVITY: 32, NEEDS_SUPPORT: 64, TOOL_REQUIRED: 128 };

const blockRows = [];
const blockPropIdx = [];
for (const b of blocks) {
  let flags = 0;
  if (b.boundingBox === 'block') flags |= F.COLLIDES;
  if (b.transparent) flags |= F.TRANSPARENT;
  if (b.diggable) flags |= F.DIGGABLE;
  if (b.name === 'water' || b.name === 'lava' || b.name === 'bubble_column') flags |= F.FLUID;
  if (REPLACEABLE.has(b.name)) flags |= F.REPLACEABLE;
  if (GRAVITY.has(b.name)) flags |= F.GRAVITY;
  if (NEEDS_SUPPORT_RE.test(b.name)) flags |= F.NEEDS_SUPPORT;
  if (b.harvestTools) flags |= F.TOOL_REQUIRED;
  const start = blockPropIdx.length;
  for (const s of b.states) blockPropIdx.push(propIndex(s));
  // minimum tool tier required (0 none, 1 wood/gold, 2 stone, 3 iron, 4 diamond)
  let minTier = 0;
  if (b.harvestTools) {
    const tools = Object.keys(b.harvestTools).map((k) => itemById[+k] && itemById[+k].name).filter(Boolean);
    const rank = { wooden: 1, golden: 1, stone: 2, iron: 3, diamond: 4, netherite: 4 };
    let best = 99;
    for (const t of tools) {
      const m = /^(wooden|stone|golden|iron|diamond|netherite)_/.exec(t);
      if (m) best = Math.min(best, rank[m[1]]);
    }
    minTier = best === 99 ? 0 : best;
  }
  const d = dropFor(b);
  const itemId = itemByName[b.name] ? itemByName[b.name].id : 0;
  blockRows.push(
    `{${cstr(b.name)},${b.minStateId},${b.defaultState},${b.maxStateId - b.minStateId + 1},${start},${b.states.length},${flags},${lightOpacity(b)},${b.emitLight},${toolClass(b)},${minTier},${itemId},${fl(Math.round(b.hardness * 1000) / 1000)},${d[0]},${d[1]},${d[2]}}`
  );
}

// state -> block table (run-length via min states)
const stateToBlock = new Array(NUM_STATES).fill(0);
for (const b of blocks) for (let s = b.minStateId; s <= b.maxStateId; s++) stateToBlock[s] = b.id;

// property definitions
const valueSets = [];
const valueSetKey = new Map();
function valueSet(vals) {
  const key = vals.join('|');
  if (valueSetKey.has(key)) return valueSetKey.get(key);
  valueSets.push(vals);
  valueSetKey.set(key, valueSets.length - 1);
  return valueSets.length - 1;
}
const propRows = propDefs.map((p) => {
  const t = p.type === 'bool' ? 0 : p.type === 'int' ? 1 : 2;
  const vs = p.type === 'enum' ? valueSet(p.values) : -1;
  return `{${cstr(p.name)},${t},${p.num_values},${vs < 0 ? 'nullptr' : 'kValues' + vs}}`;
});

// ------------------------------------------------------------------ items
const foodByName = {};
for (const f of foods) foodByName[f.name] = f;
const TIER_ORDER = ['wooden', 'stone', 'iron', 'diamond', 'netherite', 'golden'];
const SWORD_DMG = [4, 5, 6, 7, 8, 4];
const AXE_DMG = [7, 9, 9, 9, 10, 7];
const PICK_DMG = [2, 3, 4, 5, 6, 2];
const SHOVEL_DMG = [2, 3, 4, 5, 6, 2];
const ARMOR_DEF = { leather: [1, 3, 2, 1], chainmail: [2, 5, 4, 1], iron: [2, 6, 5, 2], golden: [2, 5, 3, 1], diamond: [3, 8, 6, 3], netherite: [3, 8, 6, 3], turtle: [2, 0, 0, 0] };
const ARMOR_SLOT = { helmet: 0, chestplate: 1, leggings: 2, boots: 3 };
const ITEM_KIND = { NONE: 0, PICKAXE: 1, AXE: 2, SHOVEL: 3, HOE: 4, SWORD: 5, SHEARS: 6, ARMOR: 7, FOOD: 8, BOW: 9 };
const itemRows = [];
for (let id = 0; id < NUM_ITEMS; id++) {
  const it = itemById[id];
  if (!it) { itemRows.push('{"unused",0,0,0xFFFF,0,0,0,0,0,0,0}'); continue; }
  const n = it.name;
  let kind = 0, tier = 0, attack = 1, armor = 0, slot = 0;
  let m;
  if ((m = /^(wooden|stone|iron|diamond|netherite|golden)_(pickaxe|axe|shovel|hoe|sword)$/.exec(n))) {
    tier = TIER_ORDER.indexOf(m[1]);
    kind = { pickaxe: 1, axe: 2, shovel: 3, hoe: 4, sword: 5 }[m[2]];
    attack = { pickaxe: PICK_DMG, axe: AXE_DMG, shovel: SHOVEL_DMG, sword: SWORD_DMG, hoe: [1, 1, 1, 1, 1, 1] }[m[2]][tier];
  } else if (n === 'shears') kind = 6;
  else if ((m = /^(leather|chainmail|iron|golden|diamond|netherite|turtle)_(helmet|chestplate|leggings|boots)$/.exec(n))) {
    kind = 7;
    slot = ARMOR_SLOT[m[2]];
    armor = ARMOR_DEF[m[1]][slot];
  } else if (n === 'bow' || n === 'crossbow') kind = 9;
  const food = foodByName[n];
  if (food) kind = 8;
  const blockId = blockByName[n] ? blockByName[n].id : 0xFFFF;
  itemRows.push(`{${cstr(n)},${it.stackSize},${it.maxDurability || 0},${blockId},${kind},${tier},${attack},${armor},${slot},${food ? food.foodPoints : 0},${food ? Math.round(food.saturation * 10) : 0}}`);
}
// the table above has 11 fields; keep the header in sync with registry.h

// ------------------------------------------------------------------ recipes
const rcRows = [];
const rcIng = [];
let rcCount = 0;
for (const [resId, list] of Object.entries(recipes)) {
  for (const r of list) {
    rcCount++;
    if (r.inShape) {
      const h = r.inShape.length;
      const w = Math.max(...r.inShape.map((row) => row.length));
      const start = rcIng.length;
      for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
        const c = r.inShape[y][x];
        rcIng.push(c === null || c === undefined ? 0 : c);
      }
      rcRows.push(`{${r.result.id},${r.result.count},${w},${h},0,${start}}`);
    } else {
      const start = rcIng.length;
      for (const c of r.ingredients) rcIng.push(c);
      rcRows.push(`{${r.result.id},${r.result.count},${r.ingredients.length},1,1,${start}}`);
    }
  }
}

// ------------------------------------------------------------------ entities
const entRows = entities.map((e) => `{${cstr(e.name)},${e.id},${fl(e.width)},${fl(e.height)}}`);

// ------------------------------------------------------------------ write registry_data.cpp
{
  let s = HDR + '#include "mc/registry.h"\nnamespace mc {\n';
  valueSets.forEach((vals, i) => {
    s += `static const char* const kValues${i}[] = {${vals.map(cstr).join(',')}};\n`;
  });
  s += `const PropDef PROPS[${propRows.length}] = {\n${wrap(propRows, 4)}\n};\n`;
  s += `const uint16_t BLOCK_PROPS[${blockPropIdx.length}] = {\n${wrap(blockPropIdx, 24)}\n};\n`;
  s += `const BlockDef BLOCKS[NUM_BLOCKS] = {\n${blockRows.join(',\n')}\n};\n`;
  s += `const uint16_t STATE_TO_BLOCK[NUM_STATES] = {\n${wrap(stateToBlock, 32)}\n};\n`;
  s += `const ItemDef ITEMS[NUM_ITEMS] = {\n${itemRows.join(',\n')}\n};\n`;
  s += `const int NUM_RECIPES = ${rcCount};\n`;
  s += `const RecipeDef RECIPES[${rcCount}] = {\n${wrap(rcRows, 4)}\n};\n`;
  s += `const uint16_t RECIPE_INGREDIENTS[${rcIng.length}] = {\n${wrap(rcIng, 32)}\n};\n`;
  s += `const int NUM_ENTITY_TYPES = ${entities.length};\n`;
  s += `const EntityTypeDef ENTITY_TYPES[${entities.length}] = {\n${wrap(entRows, 3)}\n};\n`;
  s += `const int NUM_PROPS = ${propRows.length};\n`;
  s += '}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'registry_data.cpp'), s);
}

// ------------------------------------------------------------------ dimension codec
{
  const KEEP_BIOMES = ['ocean', 'plains', 'desert', 'mountains', 'forest', 'taiga', 'swamp', 'river', 'frozen_ocean', 'frozen_river', 'snowy_tundra', 'beach', 'jungle', 'deep_ocean', 'snowy_beach', 'birch_forest', 'dark_forest', 'snowy_taiga', 'savanna', 'badlands', 'warm_ocean', 'lukewarm_ocean', 'cold_ocean', 'deep_cold_ocean', 'sunflower_plains', 'the_void', 'wooded_hills', 'stone_shore', 'mushroom_fields'];
  const codec = loginPacket.dimensionCodec;
  const dimTypes = codec.value['minecraft:dimension_type'].value.value.value.value;
  const overworld = dimTypes.find((d) => d.name.value === 'minecraft:overworld');
  const biomeList = codec.value['minecraft:worldgen/biome'].value.value.value.value;
  const keep = biomeList.filter((b) => KEEP_BIOMES.includes(b.name.value.replace('minecraft:', '')));
  const outCodec = JSON.parse(JSON.stringify(codec));
  outCodec.value['minecraft:dimension_type'].value.value.value.value = [overworld];
  outCodec.value['minecraft:worldgen/biome'].value.value.value.value = keep;
  const codecBuf = nbt.writeUncompressed(outCodec);
  // The dimension element sent in Join Game: the overworld's "element" compound with a nameless-root wrapper.
  const dimNbt = { type: 'compound', name: '', value: overworld.element.value };
  const dimBuf = nbt.writeUncompressed(dimNbt);
  const biomeIds = keep.map((b) => [b.name.value.replace('minecraft:', ''), b.id.value]);
  let s = HDR + '#include "mc/registry.h"\nnamespace mc {\n';
  s += `const uint8_t DIMENSION_CODEC_NBT[${codecBuf.length}] = {\n${wrap([...codecBuf], 24)}\n};\nconst size_t DIMENSION_CODEC_NBT_LEN = ${codecBuf.length};\n`;
  s += `const uint8_t DIMENSION_NBT[${dimBuf.length}] = {\n${wrap([...dimBuf], 24)}\n};\nconst size_t DIMENSION_NBT_LEN = ${dimBuf.length};\n`;
  s += '}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'codec_data.cpp'), s);
  let h = HDR + '#pragma once\n#include <stdint.h>\nnamespace mc {\nnamespace biome {  // biome ids included in the dimension codec\n';
  for (const [n, id] of biomeIds) h += `constexpr uint8_t ${camel(n)} = ${id};\n`;
  h += '}\n}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'biome_ids_gen.h'), h);
  console.log('codec bytes', codecBuf.length, 'dimension bytes', dimBuf.length, 'biomes', keep.length);
}

console.log(`blocks=${NUM_BLOCKS} states=${NUM_STATES} items=${NUM_ITEMS} props=${propDefs.length} recipes=${rcCount} entities=${entities.length}`);

// ------------------------------------------------------------------ tags (from the vanilla data pack)
{
  const tagRoot = path.join(__dirname, 'vanilla', 'data', 'minecraft', 'tags');
  if (!fs.existsSync(tagRoot)) {
    console.log('tags: tools/vanilla missing, run ./fetch_vanilla.sh first (keeping existing tags_data.cpp)');
  } else {
    const FLUIDS = { 'minecraft:empty': 0, 'minecraft:flowing_water': 1, 'minecraft:water': 2, 'minecraft:flowing_lava': 3, 'minecraft:lava': 4 };
    const entityByName = {};
    for (const e of entities) entityByName['minecraft:' + e.name] = e.id;
    const resolvers = {
      blocks: (n) => (blockByName[n.replace('minecraft:', '')] || {}).id,
      items: (n) => (itemByName[n.replace('minecraft:', '')] || {}).id,
      fluids: (n) => FLUIDS[n],
      entity_types: (n) => entityByName[n],
    };
    const readAll = (kind) => {
      const dir = path.join(tagRoot, kind);
      const out = {};
      const walk = (d, prefix) => {
        for (const f of fs.readdirSync(d)) {
          const p = path.join(d, f);
          if (fs.statSync(p).isDirectory()) walk(p, prefix + f + '/');
          else if (f.endsWith('.json')) out['minecraft:' + prefix + f.slice(0, -5)] = JSON.parse(fs.readFileSync(p)).values;
        }
      };
      walk(dir, '');
      return out;
    };
    const bytes = [];
    const varint = (v) => { do { let t = v & 0x7f; v >>>= 7; if (v) t |= 0x80; bytes.push(t); } while (v); };
    const str = (s) => { const b = Buffer.from(s, 'utf8'); varint(b.length); for (const x of b) bytes.push(x); };
    const summary = {};
    for (const kind of ['blocks', 'items', 'fluids', 'entity_types']) {
      const raw = readAll(kind);
      const cache = {};
      const resolve = (name, stack = []) => {
        if (cache[name]) return cache[name];
        if (stack.includes(name)) throw new Error('tag cycle ' + name);
        const ids = new Set();
        for (let v of raw[name] || []) {
          if (typeof v === 'object') v = v.id;
          if (v.startsWith('#')) for (const id of resolve(v.slice(1), [...stack, name])) ids.add(id);
          else {
            const id = resolvers[kind](v);
            if (id === undefined) throw new Error(`unknown ${kind} entry ${v} in ${name}`);
            ids.add(id);
          }
        }
        return (cache[name] = [...ids].sort((a, b) => a - b));
      };
      const names = Object.keys(raw).sort();
      varint(names.length);
      for (const n of names) {
        const ids = resolve(n);
        str(n);
        varint(ids.length);
        for (const id of ids) varint(id);
      }
      summary[kind] = names.length;
    }
    let s = HDR + '#include "mc/registry.h"\nnamespace mc {\n';
    s += '// Payload of the Tags packet (0x5b) without the packet id: block, item, fluid and entity tags.\n';
    s += `const uint8_t TAGS_PAYLOAD[${bytes.length}] = {\n${wrap(bytes, 24)}\n};\nconst size_t TAGS_PAYLOAD_LEN = ${bytes.length};\n}  // namespace mc\n`;
    fs.writeFileSync(path.join(OUT, 'tags_data.cpp'), s);
    console.log('tags', JSON.stringify(summary), 'bytes', bytes.length);
  }
}
