#!/usr/bin/env node
// Generates the static registry tables of the server core for Minecraft 1.21.8
// (protocol 772) from the PrismarineJS minecraft-data package and the official
// server jar's data pack (registries, tags; see fetch_vanilla.sh).
//
//   cd tools && npm install && ./fetch_vanilla.sh && node gen_data.js
//
// The generated files are committed, so you only need this to regenerate them.
'use strict';
const fs = require('fs');
const path = require('path');
const nbt = require('prismarine-nbt');

const VERSION = '1.21.8';
const PROTOCOL = 772;
const OUT = path.join(__dirname, '..', 'lib', 'mcore', 'src', 'mc', 'data');
fs.mkdirSync(OUT, { recursive: true });

const mdRoot = path.join(path.dirname(require.resolve('minecraft-data/package.json')), 'minecraft-data', 'data', 'pc');
const load = (ver, f) => JSON.parse(fs.readFileSync(path.join(mdRoot, ver, f)));
const blocks = load(VERSION, 'blocks.json');
const items = load(VERSION, 'items.json');
const entities = load(VERSION, 'entities.json');
const protocol = load(VERSION, 'protocol.json');
// minecraft-data's 1.21.8 saturation values are inconsistent (apple 19.2 instead of 2.4):
// the 1.16 values, plus the one food added since
const foods = load('1.16.1', 'foods.json').concat([{ name: 'glow_berries', foodPoints: 2, saturation: 0.4 }]);
const particles = load(VERSION, 'particles.json');
const collision = load(VERSION, 'blockCollisionShapes.json');
const blockLoot = load('1.20', 'blockLoot.json');
// the 1.16.5 tables this server was built on: block flags that minecraft-data later changed
const oldBlocks = load('1.16.2', 'blocks.json');
const VANILLA = path.join(__dirname, 'vanilla', VERSION, 'jar', 'data', 'minecraft');
if (!fs.existsSync(VANILLA)) throw new Error('tools/vanilla/' + VERSION + ' missing: run ./fetch_vanilla.sh first');

const camel = (s) => s.split(/[_/.]/).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
const fl = (x) => { let s = String(x); if (!/[.e]/i.test(s)) s += '.0'; return s + 'f'; };
const cstr = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
const HDR = `// GENERATED by tools/gen_data.js from minecraft-data and the official server jar (${VERSION} / protocol ${PROTOCOL}). DO NOT EDIT.\n`;

function wrap(arr, per = 16) {
  const lines = [];
  for (let i = 0; i < arr.length; i += per) lines.push('  ' + arr.slice(i, i + per).join(', '));
  return lines.join(',\n');
}

// blocks renamed since 1.16.5 (new name -> old name)
const RENAMED = { short_grass: 'grass', dirt_path: 'grass_path' };
const oldByName = {};
for (const b of oldBlocks) oldByName[b.name] = b;
const oldOf = (name) => oldByName[RENAMED[name] || name];

// ------------------------------------------------------------------ ids
const NUM_BLOCKS = blocks.length;
const NUM_STATES = Math.max(...blocks.map((b) => b.maxStateId)) + 1;
const maxItemId = Math.max(...items.map((i) => i.id));
const NUM_ITEMS = maxItemId + 1;
const itemById = new Array(NUM_ITEMS).fill(null);
for (const it of items) itemById[it.id] = it;
const itemByName = {};
for (const it of items) itemByName[it.name] = it;
const blockByName = {};
for (const b of blocks) blockByName[b.name] = b;
for (let i = 0; i < blocks.length; i++) if (blocks[i].id !== i) throw new Error('block ids not contiguous');

{
  let s = HDR + '#pragma once\n#include <stdint.h>\nnamespace mc {\n';
  s += `constexpr int NUM_BLOCKS = ${NUM_BLOCKS};\nconstexpr int NUM_STATES = ${NUM_STATES};\nconstexpr int NUM_ITEMS = ${NUM_ITEMS};\n`;
  s += 'namespace blk {  // block ids\n';
  for (const b of blocks) s += `constexpr uint16_t ${camel(b.name)} = ${b.id};\n`;
  s += '}\nnamespace bs {  // default block state of each block\n';
  for (const b of blocks) s += `constexpr uint16_t ${camel(b.name)} = ${b.defaultState};\n`;
  s += '}\nnamespace itm {  // item ids\n';
  for (const it of items) s += `constexpr uint16_t ${camel(it.name)} = ${it.id};\n`;
  s += '}\n}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'ids_gen.h'), s);
}

// ------------------------------------------------------------------ registries from the server jar
// minecraft-data lacks a few built-in registries. Their order is the order of registration,
// which is the order of the string constants in the registering class: find the class by
// some of its keys and read its constant pool.
function jarRegistries(queries) {
  const zlib = require('zlib');
  const jar = fs.readFileSync(path.join(__dirname, 'vanilla', VERSION, 'META-INF', 'versions', VERSION, `server-${VERSION}.jar`));
  let eocd = jar.length - 22;
  while (jar.readUInt32LE(eocd) !== 0x06054b50) eocd--;
  const count = jar.readUInt16LE(eocd + 10);
  let p = jar.readUInt32LE(eocd + 16);
  const found = {};
  for (let i = 0; i < count; i++) {
    const method = jar.readUInt16LE(p + 10), csize = jar.readUInt32LE(p + 20);
    const nlen = jar.readUInt16LE(p + 28), xlen = jar.readUInt16LE(p + 30), clen = jar.readUInt16LE(p + 32);
    const local = jar.readUInt32LE(p + 42);
    const name = jar.toString('utf8', p + 46, p + 46 + nlen);
    p += 46 + nlen + xlen + clen;
    if (!name.endsWith('.class')) continue;
    const start = local + 30 + jar.readUInt16LE(local + 26) + jar.readUInt16LE(local + 28);
    const raw = jar.subarray(start, start + csize);
    const data = method === 8 ? zlib.inflateRawSync(raw) : raw;
    for (const [key, anchors] of Object.entries(queries)) {
      if (found[key] || !anchors.every((a) => data.includes(a))) continue;
      const utf = {}, strs = [];
      const n = data.readUInt16BE(8);
      let o = 10;
      for (let k = 1; k < n; k++) {
        const t = data[o];
        if (t === 1) { const l = data.readUInt16BE(o + 1); utf[k] = data.toString('utf8', o + 3, o + 3 + l); o += 3 + l; }
        else if (t === 8) { strs.push(data.readUInt16BE(o + 1)); o += 3; }
        else if (t === 3 || t === 4) o += 5;
        else if (t === 5 || t === 6) { o += 9; k++; }
        else if (t === 7 || t === 16 || t === 19 || t === 20) o += 3;
        else if (t >= 9 && t <= 18) o += t === 15 ? 4 : 5;
        else throw new Error('constant pool tag ' + t);
      }
      found[key] = strs.map((s) => utf[s]).filter((s) => /^[a-z0-9_.]+$/.test(s));
    }
  }
  for (const k of Object.keys(queries)) if (!found[k]) throw new Error('registry not found in the jar: ' + k);
  return found;
}
const jarRegs = jarRegistries({
  block_entity_type: ['trapped_chest', 'brushable_block', 'mob_spawner'],
  menu: ['generic_9x1', 'crafter_3x3', 'stonecutter'],
});

// ------------------------------------------------------------------ protocol enumerations
const mapping = (t) => t[1].mappings;
const types = protocol.types;

// ------------------------------------------------------------------ entity ids and metadata
{
  let s = HDR + '#pragma once\n#include <stdint.h>\nnamespace mc {\nnamespace ent {  // entity type ids\n';
  for (const e of entities) s += `constexpr uint16_t ${camel(e.name)} = ${e.id};\n`;
  s += '}\n';
  // metadata: the index of each key per entity type (meta::Zombie::Baby), and the value types
  s += 'namespace meta {  // entity metadata indices per entity type\n';
  for (const e of entities) {
    if (!e.metadataKeys) continue;
    s += `namespace ${camel(e.name)} { `;
    s += e.metadataKeys.map((k, i) => `constexpr uint8_t ${camel(k)} = ${i};`).join(' ');
    s += ' }\n';
  }
  s += '}\nnamespace mt {  // entity metadata value types\n';
  const mt = mapping(types.entityMetadataEntry[1][1].type);
  for (const [id, name] of Object.entries(mt)) s += `constexpr uint8_t ${camel(name)} = ${id};\n`;
  s += '}\n}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'entity_ids_gen.h'), s);
}

// ------------------------------------------------------------------ packet ids, components, parsers
{
  const mk = (state, dir) => {
    const m = protocol[state][dir].types.packet[1][0].type[1].mappings;
    return Object.entries(m).map(([id, name]) => `constexpr uint8_t ${camel(name)} = ${parseInt(id, 16)};`).join('\n');
  };
  let s = HDR + '#pragma once\n#include <stdint.h>\nnamespace mc {\n';
  s += `constexpr int PROTOCOL_VERSION = ${PROTOCOL};\nconstexpr const char* VERSION_NAME = ${cstr(VERSION)};\n`;
  s += 'namespace pkt {\n';
  s += 'namespace login_s2c {\n' + mk('login', 'toClient') + '\n}\n';
  s += 'namespace login_c2s {\n' + mk('login', 'toServer') + '\n}\n';
  s += 'namespace cfg_s2c {  // configuration: server -> client\n' + mk('configuration', 'toClient') + '\n}\n';
  s += 'namespace cfg_c2s {  // configuration: client -> server\n' + mk('configuration', 'toServer') + '\n}\n';
  s += 'namespace s2c {  // play: server -> client\n' + mk('play', 'toClient') + '\n}\n';
  s += 'namespace c2s {  // play: client -> server\n' + mk('play', 'toServer') + '\n}\n';
  s += '}\nnamespace comp {  // item stack data component types\n';
  for (const [id, name] of Object.entries(mapping(types.SlotComponentType))) s += `constexpr uint8_t ${camel(name)} = ${id};\n`;
  s += '}\nnamespace parser {  // command argument parsers\n';
  const node = types.command_node[1].find((f) => f.name === 'extraNodeData')[1] || types.command_node[1].find((f) => f.name === 'extraNodeData').type;
  const argNode = node[1].fields['2'][1].find((f) => f.name === 'parser').type;
  for (const [id, name] of Object.entries(mapping(argNode))) s += `constexpr uint8_t ${camel(name.replace(/^(brigadier|minecraft):/, '$1_'))} = ${id};\n`;
  s += '}\nnamespace particle {  // particle type ids\n';
  for (const p of particles) s += `constexpr uint16_t ${camel(p.name)} = ${p.id};\n`;
  s += '}\nnamespace bet {  // block entity type ids\n';
  jarRegs.block_entity_type.forEach((n, i) => { s += `constexpr uint8_t ${camel(n)} = ${i};\n`; });
  s += '}\nnamespace menu {  // window (menu) type ids\n';
  jarRegs.menu.forEach((n, i) => { s += `constexpr uint8_t ${camel(n)} = ${i};\n`; });
  s += '}\n}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'packet_ids_gen.h'), s);
}

// ------------------------------------------------------------------ block data
const NEEDS_SUPPORT_RE = /(_sapling$|_tulip$|^dandelion$|^poppy$|^blue_orchid$|^allium$|^azure_bluet$|^oxeye_daisy$|^cornflower$|^lily_of_the_valley$|^wither_rose$|^sunflower$|^lilac$|^rose_bush$|^peony$|^short_grass$|^tall_grass$|^fern$|^large_fern$|^dead_bush$|^wheat$|^carrots$|^potatoes$|^beetroots$|^melon_stem$|^pumpkin_stem$|^brown_mushroom$|^red_mushroom$|^sweet_berry_bush$|^sugar_cane$|^cactus$|^nether_sprouts$|_roots$|^crimson_fungus$|^warped_fungus$|^bamboo_sapling$|^torchflower$|^torchflower_crop$|^pitcher_plant$|^pitcher_crop$|^pink_petals$|^wildflowers$|^leaf_litter$|^bush$|^firefly_bush$|_dry_grass$|^cactus_flower$|_eyeblossom$|^azalea$|^flowering_azalea$|^mangrove_propagule$|^small_dripleaf$|^big_dripleaf$|^big_dripleaf_stem$|^moss_carpet$|^pale_moss_carpet$)/;
const REPLACEABLE = new Set(['air', 'cave_air', 'void_air', 'water', 'lava', 'short_grass', 'tall_grass', 'fern', 'large_fern', 'seagrass', 'tall_seagrass', 'fire', 'soul_fire', 'vine', 'dead_bush', 'snow', 'structure_void', 'light', 'glow_lichen', 'hanging_roots', 'bush', 'short_dry_grass', 'tall_dry_grass', 'leaf_litter', 'crimson_roots', 'warped_roots', 'nether_sprouts', 'resin_clump', 'sculk_vein']);
const GRAVITY = new Set(['sand', 'red_sand', 'gravel', 'suspicious_sand', 'suspicious_gravel', 'anvil', 'chipped_anvil', 'damaged_anvil', 'dragon_egg', 'scaffolding', 'pointed_dripstone', 'white_concrete_powder', 'orange_concrete_powder', 'magenta_concrete_powder', 'light_blue_concrete_powder', 'yellow_concrete_powder', 'lime_concrete_powder', 'pink_concrete_powder', 'gray_concrete_powder', 'light_gray_concrete_powder', 'cyan_concrete_powder', 'purple_concrete_powder', 'blue_concrete_powder', 'brown_concrete_powder', 'green_concrete_powder', 'red_concrete_powder', 'black_concrete_powder']);
// the 1.16.5 server did not drop anvils, dragon eggs, scaffolding or dripstone: keep that
for (const n of ['dragon_egg', 'scaffolding', 'pointed_dripstone']) GRAVITY.delete(n);

function toolClass(b) {
  // 1 pickaxe 2 axe 3 shovel 4 hoe 5 shears/sword(special) 0 hand
  const m = b.material || '';
  if (/leaves|wool|coweb/.test(m)) return 5;
  if (/mineable\/pickaxe|incorrect_for_wooden_tool/.test(m)) return 1;
  if (/mineable\/axe/.test(m)) return 2;
  if (/mineable\/shovel/.test(m)) return 3;
  if (/mineable\/hoe/.test(m)) return 4;
  return 0;
}

const propDefs = [];
const propKey = new Map();
const blockPropIdx = [];
function propIndex(s) {
  const key = JSON.stringify([s.name, s.type, s.num_values, s.values || null]);
  if (propKey.has(key)) return propKey.get(key);
  const idx = propDefs.length;
  propDefs.push(s);
  propKey.set(key, idx);
  return idx;
}

const lootByBlock = {};
for (const l of blockLoot) lootByBlock[l.block] = l.drops;
const DROP_NONE = new Set(['air', 'cave_air', 'void_air', 'water', 'lava', 'bedrock', 'fire', 'soul_fire', 'glass', 'ice', 'frosted_ice', 'spawner', 'barrier', 'end_portal', 'end_portal_frame', 'nether_portal', 'end_gateway', 'structure_void', 'structure_block', 'jigsaw', 'command_block', 'chain_command_block', 'repeating_command_block', 'budding_amethyst', 'piston_head', 'moving_piston', 'infested_stone', 'infested_cobblestone', 'infested_stone_bricks', 'infested_mossy_stone_bricks', 'infested_cracked_stone_bricks', 'infested_chiseled_stone_bricks', 'infested_deepslate', 'vine', 'tripwire', 'turtle_egg', 'light', 'reinforced_deepslate', 'trial_spawner', 'vault', 'test_block', 'test_instance_block', 'frogspawn', 'sculk_vein', 'tinted_glass_none']);
const DROP_ALIAS = {
  stone: ['cobblestone', 1, 1], deepslate: ['cobbled_deepslate', 1, 1], grass_block: ['dirt', 1, 1], podzol: ['dirt', 1, 1], mycelium: ['dirt', 1, 1],
  coal_ore: ['coal', 1, 1], deepslate_coal_ore: ['coal', 1, 1], diamond_ore: ['diamond', 1, 1], deepslate_diamond_ore: ['diamond', 1, 1],
  emerald_ore: ['emerald', 1, 1], deepslate_emerald_ore: ['emerald', 1, 1], lapis_ore: ['lapis_lazuli', 4, 8], deepslate_lapis_ore: ['lapis_lazuli', 4, 8],
  redstone_ore: ['redstone', 4, 5], deepslate_redstone_ore: ['redstone', 4, 5], nether_quartz_ore: ['quartz', 1, 1], nether_gold_ore: ['gold_nugget', 2, 6],
  iron_ore: ['raw_iron', 1, 1], deepslate_iron_ore: ['raw_iron', 1, 1], gold_ore: ['raw_gold', 1, 1], deepslate_gold_ore: ['raw_gold', 1, 1],
  copper_ore: ['raw_copper', 2, 5], deepslate_copper_ore: ['raw_copper', 2, 5],
  glowstone: ['glowstone_dust', 2, 4], clay: ['clay_ball', 4, 4], snow_block: ['snowball', 4, 4], snow: ['snowball', 1, 1], melon: ['melon_slice', 3, 7],
  bookshelf: ['book', 3, 3], gravel: ['gravel', 1, 1], sea_lantern: ['prismarine_crystals', 2, 3], ender_chest: ['obsidian', 8, 8],
  redstone_wire: ['redstone', 1, 1], wall_torch: ['torch', 1, 1], soul_wall_torch: ['soul_torch', 1, 1], redstone_wall_torch: ['redstone_torch', 1, 1],
  dead_bush: ['stick', 0, 2], wheat: ['wheat_seeds', 1, 1], potatoes: ['potato', 1, 1], carrots: ['carrot', 1, 1], beetroots: ['beetroot_seeds', 1, 1],
  melon_stem: ['melon_seeds', 0, 0], pumpkin_stem: ['pumpkin_seeds', 0, 0], tall_grass: [null], short_grass: [null], fern: [null], large_fern: [null],
  cobweb: ['string', 1, 1], kelp_plant: ['kelp', 1, 1], bamboo_sapling: ['bamboo', 1, 1], sweet_berry_bush: ['sweet_berries', 1, 2], cocoa: ['cocoa_beans', 1, 1],
  tripwire: [null], weeping_vines_plant: [null], twisting_vines_plant: [null], nether_wart: ['nether_wart', 2, 4],
  tall_seagrass: [null], seagrass: [null], cave_vines: [null], cave_vines_plant: [null], farmland: ['dirt', 1, 1], dirt_path: ['dirt', 1, 1],
  bee_nest: [null], beehive: ['beehive', 1, 1], ancient_debris: ['ancient_debris', 1, 1], shroomlight: ['shroomlight', 1, 1],
  bush: [null], short_dry_grass: [null], tall_dry_grass: [null], hanging_roots: [null], glow_lichen: [null],
};
for (const b of blocks) {
  if (/_leaves$/.test(b.name)) DROP_ALIAS[b.name] = ['stick', 0, 2];
  let m;
  if ((m = /^(.*)_wall_(banner|sign|hanging_sign|head|skull|fan)$/.exec(b.name)) && itemByName[m[1] + '_' + m[2]]) DROP_ALIAS[b.name] = [m[1] + '_' + m[2], 1, 1];
  if ((m = /^potted_/.exec(b.name))) DROP_ALIAS[b.name] = ['flower_pot', 1, 1];
  if (/_candle_cake$|^candle_cake$/.test(b.name)) DROP_ALIAS[b.name] = [null];
}
function dropFor(b) {
  if (DROP_NONE.has(b.name) || b.name === 'bedrock' || b.hardness < 0) return [0, 0, 0];
  const al = DROP_ALIAS[b.name];
  if (al) {
    if (al[0] === null) return [0, 0, 0];
    const it = itemByName[al[0]];
    if (!it) throw new Error('drop alias item missing ' + al[0]);
    return [it.id, al[1], al[2]];
  }
  const direct = itemByName[b.name];
  if (direct) return [direct.id, 1, 1];
  const loot = lootByBlock[b.name];
  if (loot) {
    const e = loot.find((x) => x.noSilkTouch) || loot.find((x) => !x.silkTouch);
    if (e && itemByName[e.item]) return [itemByName[e.item].id, (e.stackSizeRange && e.stackSizeRange[0]) || 1, (e.stackSizeRange && e.stackSizeRange[1]) || 1];
  }
  return [0, 0, 0];
}

// Light opacity. minecraft-data's filterLight is unreliable (leaves 0, tall grass and snow
// layers 15, stairs 15), so derive it from the vanilla rules: blocks that only dim light
// by one (water, leaves, ice, cobweb, slime, honey), non-occluding blocks 0, solid cubes 15.
// Blocks that existed in 1.16.5 keep the value computed from the 1.16.5 data.
const OPACITY_ONE = new Set(['water', 'bubble_column', 'ice', 'frosted_ice', 'cobweb', 'slime_block', 'honey_block']);
const NON_OCCLUDING = /(_slab$|_stairs$|_carpet$|_bed$|_wall$|_fence$|_fence_gate$|_door$|_trapdoor$|_pane$|_bars$|^snow$|^farmland$|^dirt_path$|^soul_sand$|^lectern$|^enchanting_table$|^stonecutter$|^daylight_detector$|glass|_leaves$|^chain$|_lantern$|^lantern$|candle|_button$|_pressure_plate$|_sign$|_banner$|_head$|_skull$|^lightning_rod$|^pointed_dripstone$|amethyst_(cluster|bud)$|^decorated_pot$|^heavy_core$|^chiseled_bookshelf$|^sculk_sensor$|^calibrated_sculk_sensor$|^sculk_shrieker$|^vault$|^trial_spawner$|^copper_grate$|_copper_grate$|^mud$|^dried_ghast$|^pale_hanging_moss$|^creaking_heart$|^crafter$|^hopper$|^conduit$|^bell$|^grindstone$|^cauldron$|_cauldron$|^composter$|^scaffolding$|^spawner$|^beacon$|^anvil$|_anvil$|^end_rod$|^ladder$|^cake$|_cake$|^brewing_stand$|^campfire$|^soul_campfire$|^flower_pot$|^potted_|^dragon_egg$|^turtle_egg$|^sniffer_egg$|^sea_pickle$|^big_dripleaf$|^frogspawn$|_coral|^kelp|^honey_block$)/;
function lightOpacityOld(b) {
  if (OPACITY_ONE.has(b.name) || b.name.endsWith('_leaves')) return 1;
  if (b.transparent || b.boundingBox === 'empty') return 0;
  if (b.name === 'snow' || b.name.endsWith('_slab') || b.name.endsWith('_stairs') || b.name === 'farmland' ||
      b.name === 'grass_path' || b.name.endsWith('_carpet') || b.name === 'soul_sand' || b.name === 'lectern' ||
      b.name === 'enchanting_table' || b.name === 'stonecutter' || b.name === 'daylight_detector' || b.name.endsWith('_bed'))
    return 0;
  return 15;
}
function lightOpacity(b) {
  const o = oldOf(b.name);
  if (o) return lightOpacityOld(o);
  if (OPACITY_ONE.has(b.name) || b.name.endsWith('_leaves')) return 1;
  if (b.boundingBox === 'empty' || NON_OCCLUDING.test(b.name)) return 0;
  return b.filterLight >= 15 || !b.transparent ? 15 : 0;
}

const F = { COLLIDES: 1, TRANSPARENT: 2, DIGGABLE: 4, FLUID: 8, REPLACEABLE: 16, GRAVITY: 32, NEEDS_SUPPORT: 64, TOOL_REQUIRED: 128 };

const blockRows = [];
for (const b of blocks) {
  const o = oldOf(b.name);
  let flags = 0;
  if (b.boundingBox === 'block') flags |= F.COLLIDES;
  if (o ? o.transparent : b.transparent) flags |= F.TRANSPARENT;
  if (o ? o.diggable : b.diggable) flags |= F.DIGGABLE;
  if (b.name === 'water' || b.name === 'lava' || b.name === 'bubble_column') flags |= F.FLUID;
  if (REPLACEABLE.has(b.name)) flags |= F.REPLACEABLE;
  if (GRAVITY.has(b.name)) flags |= F.GRAVITY;
  if (NEEDS_SUPPORT_RE.test(b.name)) flags |= F.NEEDS_SUPPORT;
  if (b.harvestTools) flags |= F.TOOL_REQUIRED;
  const start = blockPropIdx.length;
  for (const s of b.states) blockPropIdx.push(propIndex(s));
  // minimum tool tier required (0 none, 1 wood/gold, 2 stone, 3 iron, 4 diamond)
  let minTier = 0;
  if (b.harvestTools) {
    const tools = Object.keys(b.harvestTools).map((k) => itemById[+k] && itemById[+k].name).filter(Boolean);
    const rank = { wooden: 1, golden: 1, stone: 2, iron: 3, diamond: 4, netherite: 4 };
    let best = 99;
    for (const t of tools) {
      const m = /^(wooden|stone|golden|iron|diamond|netherite)_/.exec(t);
      if (m) best = Math.min(best, rank[m[1]]);
    }
    minTier = best === 99 ? 0 : best;
  }
  const d = dropFor(b);
  const itemId = itemByName[b.name] ? itemByName[b.name].id : 0;
  blockRows.push(
    `{${cstr(b.name)},${b.minStateId},${b.defaultState},${b.maxStateId - b.minStateId + 1},${start},${b.states.length},${flags},${lightOpacity(b)},${b.emitLight},${toolClass(b)},${minTier},${itemId},${fl(Math.round(b.hardness * 1000) / 1000)},${d[0]},${d[1]},${d[2]}}`
  );
}

const stateToBlock = new Array(NUM_STATES).fill(0);
for (const b of blocks) for (let s = b.minStateId; s <= b.maxStateId; s++) stateToBlock[s] = b.id;

const valueSets = [];
const valueSetKey = new Map();
function valueSet(vals) {
  const key = vals.join('|');
  if (valueSetKey.has(key)) return valueSetKey.get(key);
  valueSets.push(vals);
  valueSetKey.set(key, valueSets.length - 1);
  return valueSets.length - 1;
}
const propRows = propDefs.map((p) => {
  const t = p.type === 'bool' ? 0 : p.type === 'int' ? 1 : 2;
  // ints too: their labels (repeater delay 1..4 is stored as 0..3)
  const vs = p.values ? valueSet(p.values) : -1;
  return `{${cstr(p.name)},${t},${p.num_values},${vs < 0 ? 'nullptr' : 'kValues' + vs}}`;
});

// ------------------------------------------------------------------ items
const foodByName = {};
for (const f of foods) foodByName[f.name] = f;
const TIER_ORDER = ['wooden', 'stone', 'iron', 'diamond', 'netherite', 'golden'];
const SWORD_DMG = [4, 5, 6, 7, 8, 4];
const AXE_DMG = [7, 9, 9, 9, 10, 7];
const PICK_DMG = [2, 3, 4, 5, 6, 2];
const SHOVEL_DMG = [2, 3, 4, 5, 6, 2];
const ARMOR_DEF = { leather: [1, 3, 2, 1], chainmail: [2, 5, 4, 1], iron: [2, 6, 5, 2], golden: [2, 5, 3, 1], diamond: [3, 8, 6, 3], netherite: [3, 8, 6, 3], turtle: [2, 0, 0, 0] };
const ARMOR_SLOT = { helmet: 0, chestplate: 1, leggings: 2, boots: 3 };
const itemRows = [];
// blocks placed by an item of another name (1.16.5 had the same pairs)
const ITEM_BLOCK = { redstone: 'redstone_wire', string: 'tripwire', wheat_seeds: 'wheat', carrot: 'carrots', potato: 'potatoes', beetroot_seeds: 'beetroots', melon_seeds: 'melon_stem', pumpkin_seeds: 'pumpkin_stem', sweet_berries: 'sweet_berry_bush', cocoa_beans: 'cocoa', glow_berries: 'cave_vines', torchflower_seeds: 'torchflower_crop', pitcher_pod: 'pitcher_crop' };
for (let id = 0; id < NUM_ITEMS; id++) {
  const it = itemById[id];
  if (!it) { itemRows.push('{"unused",0,0,0xFFFF,0,0,0,0,0,0,0}'); continue; }
  const n = it.name;
  let kind = 0, tier = 0, attack = 1, armor = 0, slot = 0;
  let m;
  if ((m = /^(wooden|stone|iron|diamond|netherite|golden)_(pickaxe|axe|shovel|hoe|sword)$/.exec(n))) {
    tier = TIER_ORDER.indexOf(m[1]);
    kind = { pickaxe: 1, axe: 2, shovel: 3, hoe: 4, sword: 5 }[m[2]];
    attack = { pickaxe: PICK_DMG, axe: AXE_DMG, shovel: SHOVEL_DMG, sword: SWORD_DMG, hoe: [1, 1, 1, 1, 1, 1] }[m[2]][tier];
  } else if (n === 'shears') kind = 6;
  else if ((m = /^(leather|chainmail|iron|golden|diamond|netherite|turtle)_(helmet|chestplate|leggings|boots)$/.exec(n))) {
    kind = 7;
    slot = ARMOR_SLOT[m[2]];
    armor = ARMOR_DEF[m[1]][slot];
  } else if (n === 'bow' || n === 'crossbow') kind = 9;
  const food = foodByName[n];
  if (food) kind = 8;
  const blockId = blockByName[n] ? blockByName[n].id : 0xFFFF;
  itemRows.push(`{${cstr(n)},${it.stackSize},${it.maxDurability || 0},${blockId},${kind},${tier},${attack},${armor},${slot},${food ? food.foodPoints : 0},${food ? Math.round(food.saturation * 10) : 0}}`);
}

// ------------------------------------------------------------------ recipes
// From the official data pack (data/minecraft/recipe), with item tags resolved: each
// ingredient is a set of items (#minecraft:planks is any planks). Crafting: shaped,
// shapeless and transmute (the input keeps its contents: dyeing a shulker box). The
// special recipes (fireworks, map cloning, armor dyeing, ...) are left out. Cooking:
// smelting, blasting, smoking and campfire cooking, one row per input item.
function itemTag(name, seen = new Set()) {
  name = name.replace('minecraft:', '');
  if (seen.has(name)) return [];
  seen.add(name);
  const j = JSON.parse(fs.readFileSync(path.join(VANILLA, 'tags', 'item', name + '.json')));
  const out = [];
  for (const v of j.values) {
    const s = typeof v === 'string' ? v : v.id;
    if (s.startsWith('#')) out.push(...itemTag(s.slice(1), seen));
    else out.push(s.replace('minecraft:', ''));
  }
  return out;
}
function ingredientItems(ing) {
  if (Array.isArray(ing)) return ing.flatMap(ingredientItems);
  if (typeof ing === 'string') return ing.startsWith('#') ? itemTag(ing.slice(1)) : [ing.replace('minecraft:', '')];
  if (ing.tag) return itemTag(ing.tag);
  return [ing.item.replace('minecraft:', '')];
}
const itemIdOf = (n) => {
  const it = itemByName[n.replace('minecraft:', '')];
  if (!it) throw new Error('recipe item unknown: ' + n);
  return it.id;
};
// ingredient sets, deduplicated; set 0 is "nothing"
const ingSets = [[]];
const ingSetIdx = new Map([['', 0]]);
function ingSet(ing) {
  const ids = [...new Set(ingredientItems(ing).map(itemIdOf))].sort((a, b) => a - b);
  const key = ids.join(',');
  if (!ingSetIdx.has(key)) { ingSetIdx.set(key, ingSets.length); ingSets.push(ids); }
  return ingSetIdx.get(key);
}
const rcRows = [];
const rcIng = [];
const cookRows = [];
const COOK_KIND = { 'minecraft:smelting': 1, 'minecraft:blasting': 2, 'minecraft:smoking': 4, 'minecraft:campfire_cooking': 8 };
const recipeDir = path.join(VANILLA, 'recipe');
for (const f of fs.readdirSync(recipeDir).sort()) {
  const r = JSON.parse(fs.readFileSync(path.join(recipeDir, f)));
  const res = r.result && (r.result.id || r.result.item);
  if (r.type === 'minecraft:crafting_shaped') {
    // as vanilla, without empty rows and columns at the edges (" # " is 1 wide)
    let pat = r.pattern.map((row) => row.padEnd(Math.max(...r.pattern.map((x) => x.length))));
    while (pat.length && !pat[0].trim()) pat.shift();
    while (pat.length && !pat[pat.length - 1].trim()) pat.pop();
    while (pat.every((row) => row[0] === ' ')) pat = pat.map((row) => row.slice(1));
    while (pat.every((row) => row[row.length - 1] === ' ')) pat = pat.map((row) => row.slice(0, -1));
    r.pattern = pat;
    const h = r.pattern.length;
    const w = Math.max(...r.pattern.map((row) => row.length));
    const start = rcIng.length;
    for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
      const ch = r.pattern[y][x];
      rcIng.push(ch === undefined || ch === ' ' ? 0 : ingSet(r.key[ch]));
    }
    rcRows.push(`{${itemIdOf(res)},${r.result.count || 1},${w},${h},0,${start}}`);
  } else if (r.type === 'minecraft:crafting_shapeless') {
    const start = rcIng.length;
    for (const ing of r.ingredients) rcIng.push(ingSet(ing));
    rcRows.push(`{${itemIdOf(res)},${r.result.count || 1},${r.ingredients.length},1,1,${start}}`);
  } else if (r.type === 'minecraft:crafting_transmute') {
    const start = rcIng.length;
    rcIng.push(ingSet(r.input), ingSet(r.material));
    rcRows.push(`{${itemIdOf(res)},${r.result.count || 1},2,1,2,${start}}`);
  } else if (COOK_KIND[r.type]) {
    for (const id of ingSets[ingSet(r.ingredient)])
      cookRows.push({ id, out: itemIdOf(res), kind: COOK_KIND[r.type], xp: Math.round((r.experience || 0) * 100) });
  }
}
// one row per input and result, the kinds that cook it or-ed together
const cookMerged = new Map();
for (const c of cookRows) {
  const k = c.id + ':' + c.out;
  const m = cookMerged.get(k);
  if (m) { m.kind |= c.kind; m.xp = Math.max(m.xp, c.xp); } else cookMerged.set(k, { ...c });
}
const cookList = [...cookMerged.values()].sort((a, b) => a.id - b.id);
// Fuels: vanilla's FuelValues#vanillaBurnTimes (in the game's code, not the data pack),
// in ticks; tags resolved here, the non-flammable woods (crimson, warped) taken out.
const FUEL_SOURCES = [
  ['lava_bucket', 20000], ['coal_block', 16000], ['blaze_rod', 2400], ['coal', 1600], ['charcoal', 1600],
  ['#logs', 300], ['#bamboo_blocks', 300], ['#planks', 300], ['bamboo_mosaic', 300], ['#wooden_stairs', 300],
  ['bamboo_mosaic_stairs', 300], ['#wooden_slabs', 150], ['bamboo_mosaic_slab', 150], ['#wooden_trapdoors', 300],
  ['#wooden_pressure_plates', 300], ['#wooden_fences', 300], ['#fence_gates', 300], ['note_block', 300],
  ['bookshelf', 300], ['chiseled_bookshelf', 300], ['lectern', 300], ['jukebox', 300], ['chest', 300],
  ['trapped_chest', 300], ['crafting_table', 300], ['daylight_detector', 300], ['#banners', 300], ['bow', 300],
  ['fishing_rod', 300], ['ladder', 300], ['#signs', 200], ['#hanging_signs', 800], ['wooden_shovel', 200],
  ['wooden_sword', 200], ['wooden_hoe', 200], ['wooden_axe', 200], ['wooden_pickaxe', 200], ['#wooden_doors', 200],
  ['#boats', 1200], ['#wool', 100], ['#wooden_buttons', 100], ['stick', 100], ['#saplings', 100], ['bowl', 100],
  ['#wool_carpets', 67], ['dried_kelp_block', 4001], ['crossbow', 300], ['bamboo', 50], ['dead_bush', 100],
  ['short_dry_grass', 100], ['tall_dry_grass', 100], ['scaffolding', 50], ['azalea', 100], ['flowering_azalea', 100],
  ['mangrove_roots', 300], ['leaf_litter', 100],
];
const fuelTicks = new Map();
for (const [what, ticks] of FUEL_SOURCES)
  for (const n of what.startsWith('#') ? itemTag(what.slice(1)) : [what]) fuelTicks.set(itemIdOf(n), ticks);
for (const n of itemTag('non_flammable_wood')) fuelTicks.delete(itemIdOf(n));
const fuelList = [...fuelTicks.entries()].sort((a, b) => a[0] - b[0]);

const ingStarts = [];
const ingItems = [];
for (const set of ingSets) { ingStarts.push(ingItems.length); ingItems.push(...set); }
ingStarts.push(ingItems.length);
const rcCount = rcRows.length;
if (ingSets.length > 65535 || rcIng.length > 65535) throw new Error('recipe tables too large');

// living mobs (not players, armor stands, projectiles, vehicles, displays, ...)
const MOB_TYPES = new Set(['mob', 'animal', 'ambient', 'hostile', 'water_creature', 'passive']);
const entRows = entities.map((e) => `{${cstr(e.name)},${e.id},${fl(e.width)},${fl(e.height)},${MOB_TYPES.has(e.type) ? 1 : 0}}`);

{
  let s = HDR + '#include "mc/registry.h"\nnamespace mc {\n';
  valueSets.forEach((vals, i) => {
    s += `static const char* const kValues${i}[] = {${vals.map(cstr).join(',')}};\n`;
  });
  s += `const PropDef PROPS[${propRows.length}] = {\n${wrap(propRows, 4)}\n};\n`;
  s += `const uint16_t BLOCK_PROPS[${blockPropIdx.length}] = {\n${wrap(blockPropIdx, 24)}\n};\n`;
  s += `const BlockDef BLOCKS[NUM_BLOCKS] = {\n${blockRows.join(',\n')}\n};\n`;
  s += `const uint16_t STATE_TO_BLOCK[NUM_STATES] = {\n${wrap(stateToBlock, 32)}\n};\n`;
  s += `const ItemDef ITEMS[NUM_ITEMS] = {\n${itemRows.join(',\n')}\n};\n`;
  s += `const int NUM_RECIPES = ${rcCount};\n`;
  s += `const RecipeDef RECIPES[${rcCount}] = {\n${wrap(rcRows, 4)}\n};\n`;
  s += `const uint16_t RECIPE_INGREDIENTS[${rcIng.length}] = {\n${wrap(rcIng, 32)}\n};\n`;
  s += `const int NUM_INGREDIENT_SETS = ${ingSets.length};\n`;
  s += `const uint16_t INGREDIENT_SET_START[${ingStarts.length}] = {\n${wrap(ingStarts, 32)}\n};\n`;
  s += `const uint16_t INGREDIENT_ITEMS[${ingItems.length}] = {\n${wrap(ingItems, 32)}\n};\n`;
  s += `const int NUM_COOKING = ${cookList.length};\n`;
  s += `const CookingDef COOKING[${cookList.length}] = {\n${wrap(cookList.map((c) => `{${c.id},${c.out},${c.kind},${c.xp}}`), 6)}\n};\n`;
  s += `const int NUM_FUELS = ${fuelList.length};\n`;
  s += `const FuelDef FUELS[${fuelList.length}] = {\n${wrap(fuelList.map(([id, t]) => `{${id},${t}}`), 8)}\n};\n`;
  s += `const int NUM_ENTITY_TYPES = ${entities.length};\n`;
  s += `const EntityTypeDef ENTITY_TYPES[${entities.length}] = {\n${wrap(entRows, 3)}\n};\n`;
  s += `const int NUM_PROPS = ${propRows.length};\n`;
  s += '}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'registry_data.cpp'), s);
}

// ------------------------------------------------------------------ per-state redstone, piston and collision tables
// The 1.16.5 values came from the official jar (tools/redstone/generate.py) and are kept in
// tools/redstone/states-1.16.5.json; states that existed then keep them. New blocks and
// states get theirs from rules below. Collision boxes are minecraft-data's for 1.21.8
// (checked against the jar's 1.16.5 boxes: only snow, turtle eggs and sea pickles differ,
// as in vanilla).
{
  const old = JSON.parse(fs.readFileSync(path.join(__dirname, 'redstone', 'states-1.16.5.json')));
  const stateProps = (b, s) => {   // [[name, label, index]] of state s, as minecraft-data orders them
    let rem = s - b.minStateId;
    const out = [];
    for (let i = b.states.length - 1; i >= 0; i--) {
      const p = b.states[i];
      const v = rem % p.num_values;
      rem = Math.floor(rem / p.num_values);
      const label = p.type === 'bool' ? (v === 0 ? 'true' : 'false') : p.values ? p.values[v] : String(v);
      out.unshift([p.name, label, String(v)]);
    }
    return out;
  };
  const oldIndex = (ob, props) => {   // the old state with the same values, or -1
    let idx = 0;
    for (const [name, values] of ob.props) {
      const p = props.find((x) => x[0] === name);
      if (!p) return -1;
      // by label: an int without labels in states-1.16.5.json starts at 0 ("0".."n-1");
      // minecraft-data 1.16 lists the others (delay "1".."4") with their values
      const v = values.indexOf(p[1]);
      if (v < 0) return -1;
      idx = idx * values.length + v;
    }
    return idx;
  };
  // block entities (never moved by pistons) that 1.16.5 did not have
  const NEW_BLOCK_ENTITY = /(_hanging_sign$|^crafter$|^trial_spawner$|^vault$|^decorated_pot$|sculk_sensor$|^sculk_catalyst$|^sculk_shrieker$|^chiseled_bookshelf$|^suspicious_|^creaking_heart$|^test_block$|^test_instance_block$|^brushable)/;
  const LIGHT = {   // light emission of new blocks that depends on the state
    copper_bulb: (p) => (p.lit === 'true' ? 15 : 0), exposed_copper_bulb: (p) => (p.lit === 'true' ? 12 : 0),
    weathered_copper_bulb: (p) => (p.lit === 'true' ? 8 : 0), oxidized_copper_bulb: (p) => (p.lit === 'true' ? 4 : 0),
    waxed_copper_bulb: (p) => (p.lit === 'true' ? 15 : 0), waxed_exposed_copper_bulb: (p) => (p.lit === 'true' ? 12 : 0),
    waxed_weathered_copper_bulb: (p) => (p.lit === 'true' ? 8 : 0), waxed_oxidized_copper_bulb: (p) => (p.lit === 'true' ? 4 : 0),
    light: (p) => +p.level, cave_vines: (p) => (p.berries === 'true' ? 14 : 0), cave_vines_plant: (p) => (p.berries === 'true' ? 14 : 0),
    deepslate_redstone_ore: (p) => (p.lit === 'true' ? 9 : 0), sculk_sensor: (p) => 1, calibrated_sculk_sensor: (p) => 1,
    trial_spawner: (p) => (p.trial_spawner_state === 'inactive' ? 4 : 8), vault: (p) => (p.vault_state === 'inactive' ? 6 : 12),
    creaking_heart: () => 0, firefly_bush: () => 2,
  };
  const candle = (p) => (p.lit === 'true' ? 3 * +(p.candles || 1) : 0);
  const SIGNAL = new Set(['sculk_sensor', 'calibrated_sculk_sensor', 'lightning_rod']);
  const shapeBoxes = (s, b) => {
    const e = collision.blocks[b.name];
    const id = Array.isArray(e) ? e[s - b.minStateId] : e;
    return (collision.shapes[id] || []).map((box) => box.map((v) => Math.round(v * 32)));
  };
  // the faces (D U N S W E) a shape covers completely
  const sturdy = (boxes) => {
    let mask = 0;
    const faces = [[1, 0, 0], [1, 32, 1], [2, 0, 0], [2, 32, 1], [0, 0, 0], [0, 32, 1]];
    faces.forEach(([axis, at, hi], f) => {
      const [u, v] = [0, 1, 2].filter((a) => a !== axis);
      const grid = new Uint8Array(16 * 16);
      for (const bx of boxes) {
        if (bx[axis + (hi ? 3 : 0)] !== at) continue;
        for (let i = bx[u] / 2; i < bx[u + 3] / 2; i++) for (let j = bx[v] / 2; j < bx[v + 3] / 2; j++) grid[Math.floor(i) * 16 + Math.floor(j)] = 1;
      }
      if (grid.every((g) => g)) mask |= 1 << f;
    });
    return mask;
  };
  const flagsOut = new Array(NUM_STATES), pistonOut = new Array(NUM_STATES), shapeOff = new Array(NUM_STATES);
  const shapeData = [], shapeKey = new Map();
  let carried = 0, derived = 0;
  for (const b of blocks) {
    const ob = old[RENAMED[b.name] || b.name];
    for (let s = b.minStateId; s <= b.maxStateId; s++) {
      const props = stateProps(b, s);
      const pm = Object.fromEntries(props);
      const boxes = shapeBoxes(s, b);
      const oi = ob ? oldIndex(ob, props) : -1;
      if (oi >= 0) {
        [flagsOut[s], pistonOut[s]] = ob.rows[oi];
        carried++;
      } else {
        const full = boxes.length === 1 && boxes[0].join(',') === '0,0,0,32,32,32';
        let light = b.emitLight;
        if (LIGHT[b.name]) light = LIGHT[b.name](pm);
        else if (/candle$/.test(b.name)) light = candle(pm);
        else if (/candle_cake$/.test(b.name)) light = pm.lit === 'true' ? 3 : 0;
        let f = light & 15;
        if (full && lightOpacity(b) >= 15) f |= 16;
        if (SIGNAL.has(b.name)) f |= 32;
        f |= sturdy(boxes) << 6;
        let push = 0;   // PUSH_NORMAL
        if (b.hardness < 0) push = 2 | 16;
        else if (!boxes.length && !/water|lava/.test(b.name)) push = 1;   // PUSH_DESTROY
        else if (/^(reinforced_deepslate|crying_obsidian|obsidian|respawn_anchor)$/.test(b.name)) push = 2;
        if (NEW_BLOCK_ENTITY.test(b.name)) push |= 8;
        flagsOut[s] = f;
        pistonOut[s] = push;
        derived++;
      }
      const key = boxes.map((x) => x.join(',')).join(';');
      if (!shapeKey.has(key)) {
        if (boxes.length > 15) throw new Error('too many collision boxes for ' + b.name);
        shapeKey.set(key, shapeData.length);
        shapeData.push(boxes.length);
        for (const bx of boxes) shapeData.push(...bx);
      }
      shapeOff[s] = shapeKey.get(key);
    }
  }
  if (shapeData.length >= 65536 || Math.max(...shapeData) > 127 || Math.min(...shapeData) < -128) throw new Error('collision table range');
  let s = HDR + '// bits 0..3: light; 4: conductor; 5: signal source; 6..11: sturdy faces (D U N S W E); 12..15: note instrument.\n';
  s += '#include "mc/registry.h"\nnamespace mc {\n';
  s += `const uint16_t REDSTONE_STATE_PROPERTIES[NUM_STATES] = {\n${wrap(flagsOut, 24)}\n};\n`;
  s += '// bits 0..2: PushReaction; 3: block entity; 4: unbreakable.\n';
  s += `const uint8_t PISTON_STATE_PROPERTIES[NUM_STATES] = {\n${wrap(pistonOut, 32)}\n};\n}  // namespace mc\n`;
  fs.writeFileSync(path.join(OUT, 'redstone_data.cpp'), s);
  s = HDR + '// Each shape: box count, then x0,y0,z0,x1,y1,z1 in thirty-seconds.\n#include "mc/registry.h"\nnamespace mc {\n';
  s += `const uint16_t COLLISION_SHAPE_OFFSETS[NUM_STATES] = {\n${wrap(shapeOff, 24)}\n};\n`;
  s += `const int8_t COLLISION_SHAPES[] = {\n${wrap(shapeData, 32)}\n};\n}  // namespace mc\n`;
  fs.writeFileSync(path.join(OUT, 'collision_data.cpp'), s);
  console.log(`state tables: ${carried} carried from 1.16.5, ${derived} derived; ${shapeKey.size} shapes`);
}

// The configuration packets never change: they are deflated here (zlib, as the network's
// compression), so the server does not compress tens of KB on its game loop per login.
const cfgPacketId = (name) => {
  const m = protocol.configuration.toClient.types.packet[1][0].type[1].mappings;
  return parseInt(Object.keys(m).find((k) => m[k] === name), 16);
};
function deflatedPacket(id, payload) {
  const v = [];
  do { let t = id & 0x7f; id >>>= 7; if (id) t |= 0x80; v.push(t); } while (id);
  return require('zlib').deflateSync(Buffer.concat([Buffer.from(v), Buffer.from(payload)]), { level: 9 });
}

// ------------------------------------------------------------------ synchronized registries (configuration state)
// Sent as registry_data packets. Entries carry no data for a client with the
// minecraft:core pack (it has them); see entryData.
const OVERWORLD_MIN_Y = -64, OVERWORLD_HEIGHT = 384;   // vanilla's (the server's chunks too)
const SYNCED = ['worldgen/biome', 'chat_type', 'trim_pattern', 'trim_material', 'wolf_variant', 'wolf_sound_variant', 'pig_variant',
  'frog_variant', 'cat_variant', 'cow_variant', 'chicken_variant', 'painting_variant', 'dimension_type', 'damage_type', 'banner_pattern',
  'enchantment', 'jukebox_song', 'instrument', 'test_environment', 'test_instance', 'dialog'];
const listEntries = (reg) => {
  const dir = path.join(VANILLA, reg);
  const out = [];
  const walk = (d, prefix) => {
    for (const f of fs.readdirSync(d).sort()) {
      const p = path.join(d, f);
      if (fs.statSync(p).isDirectory()) walk(p, prefix + f + '/');
      else if (f.endsWith('.json')) out.push(prefix + f.slice(0, -5));
    }
  };
  walk(dir, '');
  return out.sort();
};
const registryIds = {};
for (const r of SYNCED) registryIds[r] = listEntries(r);

// JSON -> network NBT. Whole numbers become ints, others floats, booleans bytes.
function toNbt(v) {
  if (typeof v === 'boolean') return { type: 'byte', value: v ? 1 : 0 };
  if (typeof v === 'number') return Number.isInteger(v) ? { type: 'int', value: v } : { type: 'float', value: v };
  if (typeof v === 'string') return { type: 'string', value: v };
  if (Array.isArray(v)) {
    const items = v.map(toNbt);
    const t = items.length ? items[0].type : 'end';
    return { type: 'list', value: { type: t, value: items.map((x) => x.value) } };
  }
  const value = {};
  for (const [k, x] of Object.entries(v)) value[k] = toNbt(x);
  return { type: 'compound', value };
}
const anonNbt = (obj) => {
  const full = nbt.writeUncompressed({ type: 'compound', name: '', value: toNbt(obj).value });
  // network NBT (1.20.2+): the root compound has no name: drop the empty name's length
  return Buffer.concat([full.subarray(0, 1), full.subarray(3)]);
};
const readJson = (reg, e) => JSON.parse(fs.readFileSync(path.join(VANILLA, reg, e + '.json')));
const BIOME_KEEP = ['has_precipitation', 'temperature', 'temperature_modifier', 'downfall'];
const EFFECT_KEEP = ['fog_color', 'water_color', 'water_fog_color', 'sky_color', 'foliage_color', 'dry_foliage_color', 'grass_color', 'grass_color_modifier'];
// The data of an entry. A client with the minecraft:core pack (the vanilla client) takes
// every entry's data from its own copy, so it gets names only, as from a vanilla server
// (the server uses vanilla's dimension types unchanged). Clients without the pack
// (mineflayer, the tests) get the data of every entry (full); that copy of Mojang's data
// is in registry_full_data.cpp, which the prebuilt firmware leaves out
// (MC_NO_REGISTRY_DATA).
function entryData(reg, e, full) {
  if (!full) return null;
  if (reg === 'dimension_type') {
    const d = readJson(reg, e);
    if (e === 'overworld' && (d.min_y !== OVERWORLD_MIN_Y || d.height !== OVERWORLD_HEIGHT))
      throw new Error('the overworld\'s dimension type changed: ' + d.min_y + ' ' + d.height);
    return anonNbt(d);
  }
  if (reg === 'worldgen/biome') {   // what mineflayer reads
    const b = readJson(reg, e);
    const out = {};
    for (const k of BIOME_KEEP) if (k in b) out[k] = b[k];
    out.effects = {};
    for (const k of EFFECT_KEEP) if (k in b.effects) out.effects[k] = b.effects[k];
    return anonNbt(out);
  }
  return anonNbt(readJson(reg, e));
}
{
  const regId = cfgPacketId('registry_data');
  // one byte array per variant: the payloads, then each payload deflated with its id
  function payloads(full) {
    const bytes = [];
    const offsets = [];
    const varint = (v) => { do { let t = v & 0x7f; v >>>= 7; if (v) t |= 0x80; bytes.push(t); } while (v); };
    const str = (s) => { const b = Buffer.from(s, 'utf8'); varint(b.length); for (const x of b) bytes.push(x); };
    for (const reg of SYNCED) {
      const start = bytes.length;
      str('minecraft:' + reg);
      varint(registryIds[reg].length);
      for (const e of registryIds[reg]) {
        str('minecraft:' + e);
        const d = entryData(reg, e, full);
        bytes.push(d ? 1 : 0);
        if (d) for (const x of d) bytes.push(x);
      }
      offsets.push([start, bytes.length - start]);
    }
    const zBytes = [], zOffsets = [];
    for (const [o, l] of offsets) {
      const z = deflatedPacket(regId, bytes.slice(o, o + l));
      zOffsets.push([zBytes.length, z.length]);
      for (const x of z) zBytes.push(x);
    }
    return { bytes, offsets, zBytes, zOffsets };
  }
  function emit(prefix, arr, p) {
    let s = `static const uint8_t ${arr}_BYTES[${p.bytes.length}] = {\n${wrap(p.bytes, 24)}\n};\n`;
    s += `const uint8_t* const ${prefix}[${SYNCED.length}] = {${p.offsets.map(([o]) => arr + '_BYTES + ' + o).join(', ')}};\n`;
    s += `const size_t ${prefix}_LEN[${SYNCED.length}] = {${p.offsets.map(([, l]) => l).join(', ')}};\n`;
    s += `static const uint8_t ${arr}_Z_BYTES[${p.zBytes.length}] = {\n${wrap(p.zBytes, 24)}\n};\n`;
    s += `const uint8_t* const ${prefix}_Z[${SYNCED.length}] = {${p.zOffsets.map(([o]) => arr + '_Z_BYTES + ' + o).join(', ')}};\n`;
    s += `const size_t ${prefix}_Z_LEN[${SYNCED.length}] = {${p.zOffsets.map(([, l]) => l).join(', ')}};\n`;
    return s;
  }
  const names = payloads(false), full = payloads(true);
  const bytes = names.bytes;
  let f = HDR + '// Every registry entry with its data, for clients without the minecraft:core pack.\n';
  f += '// The prebuilt firmware leaves this copy of Mojang\'s data out (MC_NO_REGISTRY_DATA).\n';
  f += '#include "mc/registry.h"\n#ifndef MC_NO_REGISTRY_DATA\nnamespace mc {\n';
  f += emit('REGISTRY_PAYLOAD_FULL', 'REGISTRY_FULL', full);
  f += '}  // namespace mc\n#endif\n';
  fs.writeFileSync(path.join(OUT, 'registry_full_data.cpp'), f);
  console.log('registries: names', names.bytes.length, 'bytes (' + names.zBytes.length + ' deflated), full',
    full.bytes.length, 'bytes (' + full.zBytes.length + ' deflated)');
  let s = HDR + '#include "mc/registry.h"\nnamespace mc {\n';
  s += '// Payloads of the configuration registry_data packets (without the packet id), one per\n';
  s += '// registry, for a client with the minecraft:core pack: names, and the changed dimension types.\n';
  s += `const int NUM_SYNCED_REGISTRIES = ${SYNCED.length};\n`;
  s += emit('REGISTRY_PAYLOAD', 'REGISTRY', names);
  const DIMS = ['overworld', 'the_nether', 'the_end'];
  s += `const char* const DIMENSION_NAME[${DIMS.length}] = {${DIMS.map((n) => cstr('minecraft:' + n)).join(', ')}};\n`;
  s += `const uint8_t DIMENSION_TYPE_ID[${DIMS.length}] = {${DIMS.map((n) => registryIds.dimension_type.indexOf(n)).join(', ')}};\n`;
  s += `const int NUM_ENCHANTMENTS = ${registryIds.enchantment.length};\n`;
  s += `const char* const ENCHANTMENT_NAME[${registryIds.enchantment.length}] = {${registryIds.enchantment.map((n) => cstr('minecraft:' + n)).join(', ')}};\n`;
  s += '}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'codec_data.cpp'), s);
  let h = HDR + '#pragma once\n#include <stdint.h>\nnamespace mc {\n';
  h += `constexpr int OVERWORLD_MIN_Y = ${OVERWORLD_MIN_Y};\nconstexpr int OVERWORLD_HEIGHT = ${OVERWORLD_HEIGHT};\n`;
  h += `constexpr int NUM_BIOMES = ${registryIds['worldgen/biome'].length};\n`;
  h += 'namespace biome {  // ids in the order of the registry_data packet\n';
  registryIds['worldgen/biome'].forEach((n, i) => { h += `constexpr uint8_t ${camel(n)} = ${i};\n`; });
  h += '}\nnamespace dmg {  // damage type ids\n';
  registryIds.damage_type.forEach((n, i) => { h += `constexpr uint8_t ${camel(n)} = ${i};\n`; });
  h += '}\nnamespace chattype {  // chat type ids\n';
  registryIds.chat_type.forEach((n, i) => { h += `constexpr uint8_t ${camel(n)} = ${i};\n`; });
  h += '}\n}  // namespace mc\n';
  fs.writeFileSync(path.join(OUT, 'biome_ids_gen.h'), h);
  console.log('registries', bytes.length, 'bytes;', SYNCED.map((r) => r + ' ' + registryIds[r].length).join(', '));
}

console.log(`blocks=${NUM_BLOCKS} states=${NUM_STATES} items=${NUM_ITEMS} props=${propDefs.length} recipes=${rcCount} cooking=${cookList.length} fuels=${fuelList.length} ingredientSets=${ingSets.length} entities=${entities.length}`);

// ------------------------------------------------------------------ tags (configuration "tags" packet)
{
  const tagRoot = path.join(VANILLA, 'tags');
  const FLUIDS = { 'minecraft:empty': 0, 'minecraft:flowing_water': 1, 'minecraft:water': 2, 'minecraft:flowing_lava': 3, 'minecraft:lava': 4 };
  const entityByName = {};
  for (const e of entities) entityByName['minecraft:' + e.name] = e.id;
  const byIndex = (list) => (n) => { const i = list.indexOf(n.replace('minecraft:', '')); return i < 0 ? undefined : i; };
  const KINDS = {   // tag folder -> [registry, resolver]
    block: ['block', (n) => (blockByName[n.replace('minecraft:', '')] || {}).id],
    item: ['item', (n) => (itemByName[n.replace('minecraft:', '')] || {}).id],
    fluid: ['fluid', (n) => FLUIDS[n]],
    entity_type: ['entity_type', (n) => entityByName[n]],
    damage_type: ['damage_type', byIndex(registryIds.damage_type)],
    'worldgen/biome': ['worldgen/biome', byIndex(registryIds['worldgen/biome'])],
    // the vanilla client refuses registries whose entries name tags it did not get
    // (enchantments: exclusive_set/..., dialogs: quick_actions, ...)
    banner_pattern: ['banner_pattern', byIndex(registryIds.banner_pattern)],
    dialog: ['dialog', byIndex(registryIds.dialog)],
    enchantment: ['enchantment', byIndex(registryIds.enchantment)],
    instrument: ['instrument', byIndex(registryIds.instrument)],
    painting_variant: ['painting_variant', byIndex(registryIds.painting_variant)],
  };
  const readAll = (kind) => {
    const dir = path.join(tagRoot, kind);
    const out = {};
    const walk = (d, prefix) => {
      for (const f of fs.readdirSync(d)) {
        const p = path.join(d, f);
        if (fs.statSync(p).isDirectory()) walk(p, prefix + f + '/');
        else if (f.endsWith('.json')) out['minecraft:' + prefix + f.slice(0, -5)] = JSON.parse(fs.readFileSync(p)).values;
      }
    };
    walk(dir, '');
    return out;
  };
  const bytes = [];
  const varint = (v) => { do { let t = v & 0x7f; v >>>= 7; if (v) t |= 0x80; bytes.push(t); } while (v); };
  const str = (s) => { const b = Buffer.from(s, 'utf8'); varint(b.length); for (const x of b) bytes.push(x); };
  const summary = {};
  varint(Object.keys(KINDS).length);
  for (const [kind, [reg, resolver]] of Object.entries(KINDS)) {
    const raw = readAll(kind);
    const cache = {};
    const resolve = (name, stack = []) => {
      if (cache[name]) return cache[name];
      if (stack.includes(name)) throw new Error('tag cycle ' + name);
      const ids = new Set();
      for (let v of raw[name] || []) {
        let required = true;
        if (typeof v === 'object') { required = v.required !== false; v = v.id; }
        if (v.startsWith('#')) { for (const id of resolve(v.slice(1), [...stack, name])) ids.add(id); continue; }
        const id = resolver(v);
        if (id === undefined) { if (required) throw new Error(`unknown ${kind} entry ${v} in ${name}`); continue; }
        ids.add(id);
      }
      return (cache[name] = [...ids].sort((a, b) => a - b));
    };
    const names = Object.keys(raw).sort();
    str('minecraft:' + reg);
    varint(names.length);
    for (const n of names) {
      const ids = resolve(n);
      str(n);
      varint(ids.length);
      for (const id of ids) varint(id);
    }
    summary[kind] = names.length;
  }
  let s = HDR + '#include "mc/registry.h"\nnamespace mc {\n';
  s += '// Payload of the configuration tags packet without the packet id.\n';
  s += `const uint8_t TAGS_PAYLOAD[${bytes.length}] = {\n${wrap(bytes, 24)}\n};\nconst size_t TAGS_PAYLOAD_LEN = ${bytes.length};\n`;
  const z = deflatedPacket(cfgPacketId('tags'), bytes);
  s += '// The packet deflated (id included), for compressed connections.\n';
  s += `const uint8_t TAGS_PAYLOAD_Z[${z.length}] = {\n${wrap([...z], 24)}\n};\nconst size_t TAGS_PAYLOAD_Z_LEN = ${z.length};\n}  // namespace mc\n`;
  console.log('tags deflated:', z.length, 'bytes');
  fs.writeFileSync(path.join(OUT, 'tags_data.cpp'), s);
  console.log('tags', JSON.stringify(summary), 'bytes', bytes.length);
}
