#!/usr/bin/env node
// Packs the dashboard page (tools/dashboard/index.html) into the firmware: gzipped,
// as a C array in lib/mcore/src/mc/server/dashboard_page.h (served as it is, with
// Content-Encoding: gzip).
//
//   node tools/gen_dashboard.js          writes the header
//   node tools/gen_dashboard.js --check  exits 1 if the header is out of date
//
// The generated header is committed, so a build needs no Node.js.
'use strict';
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');
const crypto = require('crypto');

const SRC = path.join(__dirname, 'dashboard', 'index.html');
const OUT = path.join(__dirname, '..', 'lib', 'mcore', 'src', 'mc', 'server', 'dashboard_page.h');

// LF line endings whatever the checkout has (core.autocrlf), so the output is the same
const html = Buffer.from(fs.readFileSync(SRC, 'utf8').replace(/\r\n/g, '\n'));
const gz = zlib.gzipSync(html, { level: 9 });
gz[9] = 0xff;   // the gzip header's OS byte differs between platforms: "unknown"
const etag = crypto.createHash('sha1').update(gz).digest('hex').slice(0, 12);

const lines = [];
for (let i = 0; i < gz.length; i += 24) lines.push('    ' + [...gz.subarray(i, i + 24)].map((b) => b + ',').join(''));
const text = `// Generated by tools/gen_dashboard.js from tools/dashboard/index.html: do not edit.
// The dashboard page, gzipped (${html.length} bytes, ${gz.length} gzipped).
#pragma once
#include <stddef.h>
#include <stdint.h>
namespace mc {
static const uint8_t DASHBOARD_PAGE_GZ[] = {
${lines.join('\n')}
};
static const size_t DASHBOARD_PAGE_GZ_LEN = sizeof(DASHBOARD_PAGE_GZ);
static const char DASHBOARD_PAGE_ETAG[] = "\\"${etag}\\"";
}  // namespace mc
`;

if (process.argv.includes('--check')) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') : '';
    if (cur !== text) {
        console.error('dashboard_page.h is out of date: run node tools/gen_dashboard.js');
        process.exit(1);
    }
    console.log('dashboard_page.h is up to date');
} else {
    fs.writeFileSync(OUT, text);
    console.log(`dashboard_page.h: ${html.length} bytes, ${gz.length} gzipped, etag ${etag}`);
}
