#!/usr/bin/env node
// Compiles vanilla's noise router (tools/vanilla/1.21.8 data pack) into the compact tables
// of lib/mcore/src/mc/world/vanilla/router_data.cpp: density function nodes (a DAG: named
// functions are shared), cubic splines and noise parameters. The evaluator is density.cpp.
//   node tools/worldgen/compile_router.js [overworld]
'use strict';
const fs = require('fs');
const path = require('path');

const W = path.join(__dirname, '..', 'vanilla', '1.21.8', 'jar', 'data', 'minecraft', 'worldgen');
const OUT = path.join(__dirname, '..', '..', 'lib', 'mcore', 'src', 'mc', 'world', 'vanilla', 'router_data.cpp');
const read = (sub, id) => JSON.parse(fs.readFileSync(path.join(W, sub, id.replace(/^minecraft:/, '') + '.json')));
const preset = process.argv[2] || 'overworld';
const settings = read('noise_settings', preset);

const OPS = ['constant', 'add', 'mul', 'min', 'max', 'abs', 'square', 'cube', 'half_negative', 'quarter_negative', 'squeeze',
  'clamp', 'y_clamped_gradient', 'range_choice', 'noise', 'shifted_noise', 'shift_a', 'shift_b', 'shift',
  'weird_scaled_sampler', 'old_blended_noise', 'spline', 'interpolated', 'flat_cache', 'cache_2d', 'cache_once',
  'cache_all_in_cell', 'blend_alpha', 'blend_offset', 'blend_density', 'beardifier', 'end_islands'];
const nodes = [], named = new Map(), noises = [], noiseIndex = new Map(), amps = [];
const splines = [], points = [];

function noise(id) {
  id = id.replace(/^minecraft:/, '');
  if (noiseIndex.has(id)) return noiseIndex.get(id);
  const n = read('noise', id);
  noiseIndex.set(id, noises.length);
  noises.push({ id, first: n.firstOctave, start: amps.length, count: n.amplitudes.length });
  amps.push(...n.amplitudes);
  return noises.length - 1;
}

function compile(df) {
  if (typeof df === 'number') return add({ op: 'constant', p: [df] });
  if (typeof df === 'string') {
    if (named.has(df)) return named.get(df);
    const i = compile(read('density_function', df));
    named.set(df, i);
    nodes[i].name = df.replace(/^minecraft:/, '');
    return i;
  }
  const op = df.type.replace(/^minecraft:/, '');
  if (!OPS.includes(op)) throw new Error('density function type ' + op);
  switch (op) {
    case 'add': case 'mul': case 'min': case 'max':
      return add({ op, a: compile(df.argument1), b: compile(df.argument2) });
    case 'abs': case 'square': case 'cube': case 'half_negative': case 'quarter_negative': case 'squeeze':
    case 'interpolated': case 'flat_cache': case 'cache_2d': case 'cache_once': case 'cache_all_in_cell': case 'blend_density':
      return add({ op, a: compile(df.argument) });
    case 'clamp': return add({ op, a: compile(df.input), p: [df.min, df.max] });
    case 'y_clamped_gradient': return add({ op, p: [df.from_y, df.to_y, df.from_value, df.to_value] });
    case 'range_choice':
      return add({ op, a: compile(df.input), b: compile(df.when_in_range), c: compile(df.when_out_of_range),
        p: [df.min_inclusive, df.max_exclusive] });
    case 'noise': return add({ op, noise: noise(df.noise), p: [df.xz_scale, df.y_scale] });
    case 'shifted_noise':
      return add({ op, a: compile(df.shift_x), b: compile(df.shift_y), c: compile(df.shift_z), noise: noise(df.noise),
        p: [df.xz_scale, df.y_scale] });
    case 'shift_a': case 'shift_b': case 'shift': return add({ op, noise: noise(df.argument) });
    case 'weird_scaled_sampler':
      return add({ op, a: compile(df.input), noise: noise(df.noise), aux: df.rarity_value_mapper.endsWith('type_1') ? 1 : 2 });
    case 'old_blended_noise':
      return add({ op, p: [df.xz_scale, df.y_scale, df.xz_factor, df.y_factor, df.smear_scale_multiplier] });
    case 'spline': return add({ op, noise: spline(df.spline) });
    default: return add({ op });   // blend_alpha (1), blend_offset (0), beardifier (0), end_islands
  }
}
function add(n) {
  nodes.push(n);
  return nodes.length - 1;
}
function spline(sp) {
  const coord = compile(sp.coordinate);
  const i = splines.length;
  splines.push(null);
  const pts = sp.points.map((pt) => ({
    loc: pt.location, der: pt.derivative,
    value: typeof pt.value === 'number' ? pt.value : 0,
    sub: typeof pt.value === 'number' ? -1 : spline(pt.value),
  }));
  splines[i] = { coord, first: points.length, count: pts.length };
  points.push(...pts);
  return i;
}

const ROOTS = ['final_density', 'temperature', 'vegetation', 'continents', 'erosion', 'depth', 'ridges'];
const roots = ROOTS.map((r) => compile(settings.noise_router[r]));

const f = (x) => { let s = String(Math.fround(x)); if (!/[.e]/.test(s)) s += '.0'; return s + 'f'; };
let s = '// GENERATED by tools/worldgen/compile_router.js from the vanilla 1.21.8 data pack (noise_settings/' + preset + '). DO NOT EDIT.\n';
s += '#include "mc/world/vanilla/density.h"\nnamespace mc {\nnamespace vanilla {\n';
s += `const DfNode DF_NODES[${nodes.length}] = {\n` + nodes.map((n) => {
  const p = (n.p || []).concat([0, 0, 0, 0, 0]).slice(0, 5);
  return `  {DF_${n.op.toUpperCase()}, ${n.aux || 0}, ${n.a ?? -1}, ${n.b ?? -1}, ${n.c ?? -1}, ${n.noise ?? 0}, {${p.map(f).join(', ')}}},` +
    (n.name ? ` // ${n.name}` : '');
}).join('\n') + '\n};\n';
s += `const int NUM_DF_NODES = ${nodes.length};\n`;
s += `const SplineDef DF_SPLINES[${splines.length}] = {\n` + splines.map((x) => `  {${x.coord}, ${x.first}, ${x.count}},`).join('\n') + '\n};\n';
s += `const SplinePoint DF_SPLINE_POINTS[${points.length}] = {\n` +
  points.map((p) => `  {${f(p.loc)}, ${f(p.der)}, ${f(p.value)}, ${p.sub}},`).join('\n') + '\n};\n';
s += `const NoiseDef DF_NOISES[${noises.length}] = {\n` + noises.map((n) => `  {${n.first}, ${n.count}, ${n.start}}, // ${n.id}`).join('\n') + '\n};\n';
s += `const int NUM_DF_NOISES = ${noises.length};\n`;
s += `const float DF_AMPLITUDES[${amps.length}] = {${amps.map(f).join(', ')}};\n`;
s += `const int16_t DF_ROOTS[${ROOTS.length}] = {${roots.join(', ')}};   // ${ROOTS.join(', ')}\n`;
s += `const RouterShape DF_SHAPE = {${settings.noise.min_y}, ${settings.noise.height}, ${settings.noise.size_horizontal * 4}, ${settings.noise.size_vertical * 4}, ${settings.sea_level}};\n`;
s += '}  // namespace vanilla\n}  // namespace mc\n';
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, s);
console.log(`${nodes.length} nodes, ${splines.length} splines (${points.length} points), ${noises.length} noises (${amps.length} octaves)`);

// ------------------------------------------------------------------ the router as C code
// One function per node: direct calls instead of the interpreter's dispatch, constants
// inlined, memoised only where a node has several parents (or is a cell's corner value).
{
  const refs = new Array(nodes.length).fill(0);
  const kids = (n) => [n.a, n.b, n.c].filter((k) => k !== undefined && k >= 0);
  nodes.forEach((n) => kids(n).forEach((k) => refs[k]++));
  splines.forEach((sp) => { refs[sp.coord]++; });
  nodes.forEach((n) => { if (n.op === 'interpolated') refs[n.a] += 2; });   // also evaluated by the corner pass
  roots.forEach((r) => { refs[r] += 2; });
  const call = (i) => (nodes[i].op === 'constant' ? f(nodes[i].p[0]) : `n${i}(r, x, y, z)`);
  let g = '// GENERATED by tools/worldgen/compile_router.js (the router as C code). DO NOT EDIT.\n';
  g += '#include <math.h>\n#include "mc/world/vanilla/density.h"\nnamespace mc {\nnamespace vanilla {\nnamespace {\n';
  g += 'inline float clampf(float v, float lo, float hi) { return v < lo ? lo : v > hi ? hi : v; }\n';
  g += 'inline float lerpf(float t, float a, float b) { return a + t * (b - a); }\n';
  g += nodes.map((_, i) => `float n${i}(Router& r, int x, int y, int z);`).join('\n') + '\n';
  g += splines.map((_, i) => `float s${i}(Router& r, int x, int y, int z);`).join('\n') + '\n';
  nodes.forEach((n, i) => {
    const p = n.p || [];
    let body;
    switch (n.op) {
      case 'constant': body = `return ${f(p[0])};`; break;
      case 'add': body = `v = ${call(n.a)} + ${call(n.b)};`; break;
      case 'mul': body = `{ float a = ${call(n.a)}; v = a == 0 ? 0 : a * ${call(n.b)}; }`; break;
      case 'min': body = `v = fminf(${call(n.a)}, ${call(n.b)});`; break;
      case 'max': body = `v = fmaxf(${call(n.a)}, ${call(n.b)});`; break;
      case 'abs': body = `v = fabsf(${call(n.a)});`; break;
      case 'square': body = `{ float a = ${call(n.a)}; v = a * a; }`; break;
      case 'cube': body = `{ float a = ${call(n.a)}; v = a * a * a; }`; break;
      case 'half_negative': body = `{ float a = ${call(n.a)}; v = a > 0 ? a : a * 0.5f; }`; break;
      case 'quarter_negative': body = `{ float a = ${call(n.a)}; v = a > 0 ? a : a * 0.25f; }`; break;
      case 'squeeze': body = `{ float c = clampf(${call(n.a)}, -1, 1); v = c / 2 - c * c * c / 24; }`; break;
      case 'clamp': body = `v = clampf(${call(n.a)}, ${f(p[0])}, ${f(p[1])});`; break;
      case 'y_clamped_gradient': {
        body = `{ float t = ((float)y - ${f(p[0])}) / (${f(p[1])} - ${f(p[0])}); ` +
          `v = t < 0 ? ${f(p[2])} : t > 1 ? ${f(p[3])} : lerpf(t, ${f(p[2])}, ${f(p[3])}); }`;
        break;
      }
      case 'range_choice':
        body = `{ float a = ${call(n.a)}; v = a >= ${f(p[0])} && a < ${f(p[1])} ? ${call(n.b)} : ${call(n.c)}; }`;
        break;
      case 'noise': body = `v = r.noiseValue(${n.noise}, x * ${f(p[0])}, y * ${f(p[1])}, z * ${f(p[0])});`; break;
      case 'shifted_noise':
        body = `v = r.noiseValue(${n.noise}, x * ${f(p[0])} + ${call(n.a)}, y * ${f(p[1])} + ${call(n.b)}, z * ${f(p[0])} + ${call(n.c)});`;
        break;
      case 'shift_a': body = `v = r.noiseValue(${n.noise}, x * 0.25f, 0, z * 0.25f) * 4;`; break;
      case 'shift_b': body = `v = r.noiseValue(${n.noise}, z * 0.25f, x * 0.25f, 0) * 4;`; break;
      case 'shift': body = `v = r.noiseValue(${n.noise}, x * 0.25f, y * 0.25f, z * 0.25f) * 4;`; break;
      case 'weird_scaled_sampler':
        body = `{ float a = ${call(n.a)}, q = ` + (n.aux === 1
          ? 'a < -0.5f ? 0.75f : a < 0 ? 1.0f : a < 0.5f ? 1.5f : 2.0f'
          : 'a < -0.75f ? 0.5f : a < -0.5f ? 0.75f : a < 0.5f ? 1.0f : a < 0.75f ? 2.0f : 3.0f') +
          `; v = q * fabsf(r.noiseValue(${n.noise}, x / q, y / q, z / q)); }`;
        break;
      case 'old_blended_noise': body = `v = r.blended(DF_NODES[${i}], x, y, z);`; break;
      case 'spline': body = `v = s${n.noise}(r, x, y, z);`; break;
      case 'interpolated': body = `v = r.corners_ ? ${call(n.a)} : r.interpNow_[r.interpSlot_[${i}]];`; break;
      case 'flat_cache': case 'cache_2d': {
        const flat = n.op === 'flat_cache';
        body = `{ int cx = ${flat ? 'x & ~3' : 'x'}, cz = ${flat ? 'z & ~3' : 'z'};
    int32_t key = (int32_t)(((uint32_t)cx & 0xFFFF) << 16 | ((uint32_t)cz & 0xFFFF));
    if (r.cacheKey_[${i}] == key && r.memoStamp_[${i}] != 0) v = r.memo_[${i}];
    else { uint32_t saved = r.stamp_; r.stamp_ = ++r.stampCounter_; v = ${`n${n.a}(r, cx, ${flat ? '0' : 'y'}, cz)`}; r.stamp_ = saved; r.cacheKey_[${i}] = key; } }`;
        break;
      }
      case 'cache_once': case 'cache_all_in_cell': case 'blend_density': body = `v = ${call(n.a)};`; break;
      case 'blend_alpha': body = 'return 1;'; break;
      default: body = 'return 0;'; break;
    }
    const memo = refs[i] > 1 || n.op === 'flat_cache' || n.op === 'cache_2d';
    g += `float n${i}(Router& r, int x, int y, int z) {`;
    if (body.startsWith('return')) { g += ` (void)r; (void)x; (void)y; (void)z; ${body} }\n`; return; }
    if (memo) g += `\n    if (r.memoStamp_[${i}] == r.stamp_) return r.memo_[${i}];`;
    g += `\n    float v;\n    ${body}\n`;
    if (memo) g += `    r.memo_[${i}] = v;\n    r.memoStamp_[${i}] = r.stamp_;\n`;
    g += '    return v;\n}\n';
  });
  splines.forEach((sp, i) => {
    const pts = points.slice(sp.first, sp.first + sp.count);
    g += `float s${i}(Router& r, int x, int y, int z) {\n`;
    g += `    static const float loc[${pts.length}] = {${pts.map((p) => f(p.loc)).join(', ')}};\n`;
    g += `    static const float der[${pts.length}] = {${pts.map((p) => f(p.der)).join(', ')}};\n`;
    g += `    auto val = [&](int k) -> float {\n        switch (k) {\n`;
    pts.forEach((p, k) => { g += `            case ${k}: return ${p.sub >= 0 ? `s${p.sub}(r, x, y, z)` : f(p.value)};\n`; });
    g += '            default: return 0;\n        }\n    };\n';
    g += `    float c = ${call(sp.coord)};\n    int n = ${pts.length}, lo = 0, hi = n;\n`;
    g += '    while (lo < hi) { int m = (lo + hi) / 2; if (c < loc[m]) hi = m; else lo = m + 1; }\n';
    g += '    int i = lo - 1;\n';
    g += '    if (i < 0) return val(0) + der[0] * (c - loc[0]);\n';
    g += '    if (i == n - 1) return val(n - 1) + der[n - 1] * (c - loc[n - 1]);\n';
    g += '    float x0 = loc[i], x1 = loc[i + 1], t = (c - x0) / (x1 - x0), y0 = val(i), y1 = val(i + 1);\n';
    g += '    float p = der[i] * (x1 - x0) - (y1 - y0), q = -der[i + 1] * (x1 - x0) + (y1 - y0);\n';
    g += '    return lerpf(t, y0, y1) + t * (1 - t) * lerpf(t, p, q);\n}\n';
  });
  g += '}  // namespace\n';
  g += `const GenFn DF_GEN[${nodes.length}] = {${nodes.map((_, i) => `n${i}`).join(', ')}};\n`;
  g += '}  // namespace vanilla\n}  // namespace mc\n';
  fs.writeFileSync(path.join(path.dirname(OUT), 'router_gen.cpp'), g);
  console.log('router_gen.cpp', g.length, 'bytes');
}
